Repository lowRISC/opentitan, pull requests merged in 2020-02, with the labels that each got.

#1494 [lint] Add AscentLint 2019.A.p3 configuration
  hw/lint/ascentlint-config.tcl
  hw/lint/common.core
Labels: Component:RTL, Component:Tooling

#1518 [prim_assert] Fix lint error due to long lines
  hw/ip/prim/rtl/prim_assert.sv
Labels: Component:RTL

#1517 [alert_handler] Correct a wave diagram and enable condition.
  hw/ip/alert_handler/doc/_index.md
  hw/ip/alert_handler/rtl/alert_handler_reg_wrap.sv
Labels: Component:RTL

#1528 [prim_assert] This adds lint waivers for the macro line length warnings
  hw/ip/prim/lint/prim.waiver
Labels: Component:RTL

#1630 [i2c, dv] Update i2c_csr_* tests
  hw/ip/i2c/dv/env/i2c_env.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_common_vseq.sv
Labels: Component:DV
