Repository lowRISC/opentitan, pull requests merged in 2020-05, with the labels that each got.

#2036 [i2c, rtl] Various FSM fixes and improvements
  hw/ip/i2c/rtl/i2c_core.sv
  hw/ip/i2c/rtl/i2c_fsm.sv
Labels: Component:RTL

#2109 [i2c, rtl] Various FSM fixes and improvements
  hw/ip/i2c/rtl/i2c_core.sv
  hw/ip/i2c/rtl/i2c_fsm.sv
Labels: Component:RTL

#2208 [util] Fix Vendor Reset Revision
  util/vendor.py
Labels: Component:Tooling

#2269 [i2c, dv] Add reactive i2c_agent (pre-V1)
  hw/dv/sv/i2c_agent/i2c_agent.core
  hw/dv/sv/i2c_agent/i2c_agent.sv
  hw/dv/sv/i2c_agent/i2c_agent_cfg.sv
  hw/dv/sv/i2c_agent/i2c_agent_cov.sv
  hw/dv/sv/i2c_agent/i2c_agent_pkg.sv
  hw/dv/sv/i2c_agent/i2c_device_driver.sv
  hw/dv/sv/i2c_agent/i2c_driver.sv
  hw/dv/sv/i2c_agent/i2c_host_driver.sv
  hw/dv/sv/i2c_agent/i2c_if.sv
  hw/dv/sv/i2c_agent/i2c_item.sv
  hw/dv/sv/i2c_agent/i2c_monitor.sv
  hw/dv/sv/i2c_agent/i2c_sequencer.sv
  hw/dv/sv/i2c_agent/seq_lib/i2c_device_seq.sv
  hw/dv/sv/i2c_agent/seq_lib/i2c_host_seq.sv
  hw/dv/sv/i2c_agent/seq_lib/i2c_seq_list.sv
  hw/ip/i2c/data/i2c_testplan.hjson
  hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_common_vseq.sv
  hw/ip/i2c/dv/tests/i2c_base_test.sv
Labels: Component:DV

#2270 [i2c, dv] Updated documents (pre-V1)
  hw/ip/i2c/data/i2c_testplan.hjson
  hw/ip/i2c/doc/checklist.md
  hw/ip/i2c/doc/dv_plan/index.md
  hw/ip/i2c/dv/i2c_sim_cfg.hjson
Labels: Component:Doc

#2308 [sw] Ensure Generated C Headers Can Be Used By C++
  hw/top_earlgrey/data/top_earlgrey.h.tpl
  hw/top_earlgrey/sw/autogen/top_earlgrey.h
  util/reggen/gen_cheader.py
Labels: Component:SW

#1641 [mock_testing, dif_plic] Introduce PLIC mock tests
  sw/device/tests/dif/dif_plic_test.cc
  sw/device/tests/dif/meson.build
Labels: Component:SW
