Repository lowRISC/opentitan, pull requests merged in 2020-06, with the labels that each got.

#2330 [i2c, dv] Add i2c_sanity_vseq for V1
  hw/dv/sv/i2c_agent/i2c_driver.sv
  hw/dv/sv/i2c_agent/i2c_monitor.sv
  hw/dv/sv/i2c_agent/seq_lib/i2c_base_seq.sv
  hw/ip/i2c/data/i2c.hjson
  hw/ip/i2c/data/i2c_testplan.hjson
  hw/ip/i2c/dv/env/i2c_env.core
  hw/ip/i2c/dv/env/i2c_env.sv
  hw/ip/i2c/dv/env/i2c_env_cfg.sv
  hw/ip/i2c/dv/env/i2c_env_cov.sv
  hw/ip/i2c/dv/env/i2c_env_pkg.sv
  hw/ip/i2c/dv/env/i2c_scoreboard.sv
  hw/ip/i2c/dv/env/i2c_virtual_sequencer.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_common_vseq.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_rx_tx_vseq.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_sanity_vseq.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_vseq_list.sv
  hw/ip/i2c/dv/i2c_sim_cfg.hjson
Labels: Component:DV

#2409 [syn] Minor updates to synthesis scripts
  hw/syn/data/dc.hjson
  hw/syn/tools/dc/run-syn.tcl
  hw/syn/tools/dc/start-dc.sh
  hw/syn/tools/dc/testsynth.tcl
Labels: Component:Tooling

#2421 [i2c, dv] Fix incorrect bit width definition for timeout value
  hw/dv/sv/i2c_agent/i2c_agent_pkg.sv
Labels: Component:DV

#2429 rv_plic: Complete S1 review for rv_plic DIF
  hw/ip/rv_plic/data/rv_plic.prj.hjson
  sw/device/lib/dif/dif_plic.md
Labels: Component:SW

#1930 [sw/dif] Introduce an I2C DIF
  meson.build
  sw/device/lib/dif/dif_i2c.c
  sw/device/lib/dif/dif_i2c.h
  sw/device/lib/dif/meson.build
  sw/device/tests/dif/dif_i2c_unittest.cc
  sw/device/tests/dif/meson.build
Labels: Component:SW

#2521 [i2c,dv] Extend i2c_agent to verify host clock stretching
  hw/dv/sv/i2c_agent/i2c_device_driver.sv
  hw/dv/sv/i2c_agent/i2c_if.sv
  hw/ip/i2c/dv/env/i2c_env_pkg.sv
Labels: Component:DV

#2487 [prim_ram*] Add an assertion that checks wmask consistency
  hw/ip/prim_generic/rtl/prim_generic_ram_1p.sv
  hw/ip/prim_generic/rtl/prim_generic_ram_2p.sv
Labels: Component:RTL

#1966 Add tests for GPIO DIF library
  sw/device/lib/dif/dif_gpio.c
  sw/device/tests/dif/dif_gpio_unittest.cc
  sw/device/tests/dif/meson.build
Labels: Component:SW

#2582 [pwrmgr] Fix DC compilation issue and verible style warnings
  hw/ip/pwrmgr/rtl/pwrmgr_pkg.sv
Labels: Component:RTL

#2565 [i2c,dv] Update testplan for V1 sign-off
  hw/ip/i2c/data/i2c_testplan.hjson
Labels: Component:DV

#2568 [i2c, dv] Update checklist.md for V1 sign-off
  hw/ip/i2c/doc/checklist.md
Labels: Component:DV

#2578 [i2c, rtl] Checklist Update for D1 Signoff
  hw/ip/i2c/doc/checklist.md
Labels: Component:RTL

#2593 [i2c, doc] Update i2c.proj.hjson for D1 and V1 sign-off completion
  hw/ip/i2c/data/i2c.prj.hjson
Labels: Component:Doc

#2584 [syn] Print detailed messages to .md if publication is disabled
  hw/syn/data/dc.hjson
  hw/syn/tools/dc/parse-syn-report.py
  hw/syn/tools/dc/run-syn.tcl
  util/dvsim/FlowCfg.py
  util/dvsim/LintCfg.py
  util/dvsim/OneShotCfg.py
  util/dvsim/SynCfg.py
  util/dvsim/utils.py
Labels: Component:Tooling

#2610 [dvsim] Fix printout issue with triple back-ticks
  hw/lint/tools/ascentlint/parse-lint-report.py
  hw/lint/tools/veriblelint/parse-lint-report.py
  util/dvsim/LintCfg.py
  util/dvsim/utils.py
Labels: Component:Tooling

#2627 [style-lint] Fix some common style lint warnings
  hw/ip/alert_handler/rtl/alert_handler_ping_timer.sv
  hw/ip/pinmux/rtl/pinmux_pkg.sv
  hw/ip/pinmux/rtl/pinmux_wkup.sv
  hw/ip/prim/rtl/prim_packer.sv
Labels: Component:RTL

#2607 [i2c, dv] Add i2c_override test
  hw/ip/i2c/data/i2c_testplan.hjson
  hw/ip/i2c/dv/env/i2c_env.core
  hw/ip/i2c/dv/env/seq_lib/i2c_override_vseq.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_vseq_list.sv
  hw/ip/i2c/dv/i2c_sim_cfg.hjson
Labels: Component:DV

#2633 [lint/entropy_src] Add the entropy source to the lint regression
  hw/lint/Makefile
  hw/top_earlgrey/lint/top_earlgrey_lint_cfgs.hjson
Labels: Component:Tooling

#2654 [prim_cipher_pkg] Replicate common subfunctions for other widths
  hw/ip/prim/rtl/prim_cipher_pkg.sv
Labels: Component:RTL

#2606 [i2c, dv] Support chained read requests
  hw/dv/sv/i2c_agent/i2c_item.sv
  hw/dv/sv/i2c_agent/i2c_monitor.sv
  hw/ip/i2c/dv/env/i2c_env_pkg.sv
  hw/ip/i2c/dv/env/i2c_scoreboard.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_rx_tx_vseq.sv
Labels: Component:DV

#2660 [i2c, dv] Exercise interrupt logic in i2c_sanity
  hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_rx_tx_vseq.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_sanity_vseq.sv
Labels: Component:DV

#2662 [i2c, doc] Transaction complete interrupt
  hw/ip/i2c/doc/I2C_block_diagram.svg
  hw/ip/i2c/doc/I2C_state_diagram.svg
  hw/ip/i2c/doc/_index.md
Labels: Component:Doc

#2644 [i2c, rtl] Addition of transaction complete interrupt
  hw/ip/i2c/data/i2c.hjson
  hw/ip/i2c/rtl/i2c.sv
  hw/ip/i2c/rtl/i2c_core.sv
  hw/ip/i2c/rtl/i2c_fsm.sv
  hw/ip/i2c/rtl/i2c_reg_pkg.sv
  hw/ip/i2c/rtl/i2c_reg_top.sv
Labels: Component:RTL
