Repository lowRISC/opentitan, pull requests merged in 2021-11, with the labels that each got.

#8971 [alert_handler] Minor lint fix
  hw/ip_templates/alert_handler/rtl/alert_pkg.sv
  hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_pkg.sv
Labels: Component:RTL

#8973 [sram_ctrl/doc] Execution from SRAM clarifications
  hw/ip/sram_ctrl/doc/_index.md
Labels: Component:Doc

#8972 [sram_ctrl] Connect second bus integ failure
  hw/ip/sram_ctrl/rtl/sram_ctrl.sv
Labels: Component:RTL

#8979 [otp_ctrl] Convert HW_CFG EN chicken bits to mubi8 types
  hw/ip/otp_ctrl/data/otp_ctrl_img_dev.hjson
  hw/ip/otp_ctrl/data/otp_ctrl_img_rma.hjson
  hw/ip/otp_ctrl/data/otp_ctrl_mmap.hjson
  hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv
  hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv.tpl
  hw/ip/otp_ctrl/rtl/otp_ctrl_pkg.sv
  hw/ip/sram_ctrl/data/sram_ctrl.hjson
  hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_executable_vseq.sv
  hw/ip/sram_ctrl/dv/env/sram_ctrl_env_cov.sv
  hw/ip/sram_ctrl/dv/env/sram_ctrl_exec_if.sv
  hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
  hw/ip/sram_ctrl/rtl/sram_ctrl.sv
  hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
  hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
  util/design/lib/OtpMemImg.py
  util/design/lib/OtpMemMap.py
  util/design/mubi/prim_mubi.py
  util/topgen/templates/toplevel.sv.tpl
Labels: Component:Tooling, Component:RTL

#8954 [dif/rom_ctrl] Auto-generate portion of DIFs.
  meson.build
  sw/device/lib/dif/autogen/dif_rom_ctrl_autogen.c
  sw/device/lib/dif/autogen/dif_rom_ctrl_autogen.h
  sw/device/lib/dif/autogen/dif_rom_ctrl_autogen_unittest.cc
  sw/device/lib/dif/autogen/meson.build
  sw/device/lib/dif/dif_rom_ctrl.c
  sw/device/lib/dif/dif_rom_ctrl.h
  sw/device/lib/dif/dif_rom_ctrl_unittest.cc
  sw/device/lib/dif/meson.build
Labels: Component:DV, Component:SW, Type:Task

#8953 [util] Make `check_dif_statuses.py` aware of autogen DIFs.
  util/check_dif_statuses.py
Labels: Component:Tooling, Type:Cleanup

#9003 [sw/testing] Make `CHECK_BUFFER` consistent with other `CHECK*` macros.
  sw/device/lib/testing/check.h
  sw/device/lib/testing/rstmgr_testutils.c
  sw/device/lib/testing/rstmgr_testutils.h
  sw/device/tests/csrng_smoketest.c
Labels: Component:SW, Type:Cleanup

#8837 [dv] Massively shorten FOO_csr_mem_rw_with_rand_reset tests
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
  hw/ip/keymgr/dv/env/seq_lib/keymgr_common_vseq.sv
Labels: Component:DV, Type:Cleanup

#9034 [clkmgr/dif] Align DIF to use mubi type
  sw/device/lib/dif/dif_clkmgr.c
  sw/device/lib/dif/dif_clkmgr_unittest.cc
Labels: Component:SW, Priority:P0

#9029 [sysrst_ctrl/doc] Fix stale register references
  hw/ip/sysrst_ctrl/data/sysrst_ctrl.hjson
  hw/ip/sysrst_ctrl/doc/_index.md
Labels: Component:Doc

#9047 [sw/rom_ext] Rename rom_ext folder.
  sw/device/_index.md
  sw/device/silicon_creator/mask_rom/docs/_index.md
  sw/device/silicon_creator/meson.build
  sw/device/silicon_creator/rom_ext/docs/manifest.md
  sw/device/silicon_creator/rom_ext/meson.build
  sw/device/silicon_creator/rom_ext/mock_rom_ext_boot_policy_ptrs.h
  sw/device/silicon_creator/rom_ext/rom_ext.c
  sw/device/silicon_creator/rom_ext/rom_ext.h
  sw/device/silicon_creator/rom_ext/rom_ext_boot_policy.c
  sw/device/silicon_creator/rom_ext/rom_ext_boot_policy.h
  sw/device/silicon_creator/rom_ext/rom_ext_boot_policy_ptrs.h
  sw/device/silicon_creator/rom_ext/rom_ext_boot_policy_unittest.cc
  sw/device/silicon_creator/rom_ext/rom_ext_common.ld
  sw/device/silicon_creator/rom_ext/rom_ext_epmp.c
  sw/device/silicon_creator/rom_ext/rom_ext_epmp.h
  sw/device/silicon_creator/rom_ext/rom_ext_slot_a.ld
  sw/device/silicon_creator/rom_ext/rom_ext_slot_b.ld
  sw/device/silicon_creator/rom_ext/rom_ext_start.S
  sw/host/rom_ext_image_tools/signer/README.md
Labels: Type:Cleanup, Component: ROM_EXT

#9057 [syn/aes/otbn] Minor fixes to fix block level synthesis
  hw/ip/aes/syn/aes_syn_cfg.hjson
  hw/ip/otbn/syn/otbn_syn_cfg.hjson
  util/dvsim/SynCfg.py
Labels: Component:Tooling

#9059 [top/usb] Instantiate second pair of USB pads
  hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
  hw/top_earlgrey/data/top_earlgrey.hjson
  hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
  hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
  hw/top_earlgrey/rtl/autogen/chip_earlgrey_nexysvideo.sv
  hw/top_earlgrey/rtl/scan_role_pkg.sv
  hw/top_englishbreakfast/data/top_englishbreakfast.hjson
  util/topgen/gen_top_docs.py
  util/topgen/templates/chiplevel.sv.tpl
  util/topgen/validate.py
Labels: Component:RTL

#9082 [csrng / edn] Add required assertions from prim_count testing
  hw/ip/csrng/rtl/csrng.sv
  hw/ip/edn/rtl/edn.sv
Labels: Priority:P0

#9067 [sw/testing] Fix comment typos in `check.h`.
  sw/device/lib/testing/check.h
Labels: Component:SW, Type:Cleanup

#9097 [syn] Minor scripting alignment with CDC flow
  hw/syn/tools/dc/run-syn.tcl
  hw/syn/tools/dvsim/common_syn_cfg.hjson
  hw/syn/tools/dvsim/dc.hjson
Labels: Component:Tooling

#9075 [doc] Add style guide for `testutils` chip-level test libraries.
  sw/device/lib/testing/_index.md
Labels: Component:Doc

#9168 [prim] Add missing include to prim_mubi_dec*
  hw/ip/prim/rtl/prim_mubi12_dec.sv
  hw/ip/prim/rtl/prim_mubi16_dec.sv
  hw/ip/prim/rtl/prim_mubi4_dec.sv
  hw/ip/prim/rtl/prim_mubi8_dec.sv
  util/design/data/prim_mubi_dec.sv.tpl
Labels: Type:Bug, Component:RTL

#9167 [prim] Add missing include to prim_xilinx_pad_wrapper
  hw/ip/prim_xilinx/rtl/prim_xilinx_pad_wrapper.sv
Labels: Type:Bug, Component:RTL

#9140 [util] Move some generic parsing code to util
  hw/ip/otbn/dv/otbnsim/Makefile
  hw/ip/otbn/dv/otbnsim/mypy.ini
  hw/ip/otbn/dv/otbnsim/sim/ext_regs.py
  hw/ip/otbn/dv/rig/Makefile
  hw/ip/otbn/dv/rig/mypy.ini
  hw/ip/otbn/dv/rig/otbn-rig
  hw/ip/otbn/dv/rig/rig/config.py
  hw/ip/otbn/util/Makefile
  hw/ip/otbn/util/mypy.ini
  hw/ip/otbn/util/shared/__init__.py
  hw/ip/otbn/util/shared/encoding.py
  hw/ip/otbn/util/shared/encoding_scheme.py
  hw/ip/otbn/util/shared/insn_yaml.py
  hw/ip/otbn/util/shared/lsu_desc.py
  hw/ip/otbn/util/shared/mem_layout.py
  hw/ip/otbn/util/shared/operand.py
  hw/ip/otbn/util/shared/otbn_reggen.py
  util/serialize/__init__.py
  util/serialize/parse_helpers.py
Labels: Component:Tooling, Type:Cleanup

#8956 [util] Document default resval for non-hwext registers
  util/reggen/field.py
Labels: Component:Tooling, Type:Bug

#9194 [ipgen] Plumb TemplateParams through correctly
  util/ipgen.py
  util/ipgen/lib.py
Labels: Component:Tooling, Type:Bug

#9158 [sw/ottf] Optimize OTTF for non-concurrent tests.
  sw/device/lib/testing/test_framework/example_ottf_test.c
  sw/device/lib/testing/test_framework/ottf.c
  sw/device/lib/testing/test_framework/ottf.h
  sw/device/lib/testing/test_framework/test_main.c
Labels: Component:DV, Component:SW

#8806 [rstmgr] Fix width of counter in rstmgr_cnsty_chk
  hw/ip/rstmgr/rtl/rstmgr_cnsty_chk.sv
Labels: Type:Bug, Component:RTL

#9039 [util] Add script and first template to autogen (some) testutils.
  util/autogen_testutils.py
  util/autogen_testutils/isr_testutils.h.tpl
Labels: Component:DV, Component:SW, Type:Task

#9238 [ast] Add inline wavejson for waveform images
  hw/top_earlgrey/ip/ast/doc/_index.md
  hw/top_earlgrey/ip/ast/doc/media/image1.png
  hw/top_earlgrey/ip/ast/doc/media/image2.png
  hw/top_earlgrey/ip/ast/doc/media/image3.png
Labels: Component:Doc

#8957 [dv] Slightly generalise run_stress_all_with_rand_reset_vseq
  hw/dv/sv/cip_lib/doc/index.md
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
  hw/dv/sv/dv_lib/dv_base_vseq.sv
Labels: Component:DV, Type:Cleanup

#9249 [util] Remove debug prints to speed up secded_gen.py
  util/design/secded_gen.py
Labels: Component:Tooling, Type:Enhancement

#9250 [ci] Simplify check-generated.sh; allow it to catch multiple errors
  ci/scripts/check-generated.sh
Labels: Type:Cleanup, Component:CI

#9254 [doc] Minor dev stages cleanup
  doc/project/development_stages.md
Labels: Component:Doc

#9209 [sw/ottf] Fix processing of `mepc` on synchronous IRQ.
  sw/device/lib/testing/test_framework/freertos_port.S
Labels: Component:SW, Type:Bug

#9230 [sw/ottf] Restructure meson build targets for OTTF.
  sw/device/lib/testing/test_framework/example_ottf_test.c
  sw/device/lib/testing/test_framework/meson.build
  sw/device/tests/meson.build
  sw/device/tests/ottf_example_bare_metal_test.c
  sw/device/tests/ottf_example_concurrency_test.c
Labels: Component:SW, Type:Task

#9252 [otbn,dv] Fix is_valid_256b_addr check
  hw/ip/otbn/dv/otbnsim/sim/dmem.py
Labels: Component:DV, Type:Bug, Component:OTBN

#9257 [otbn,rtl] Weaken assertion about imem_addr_o
  hw/ip/otbn/rtl/otbn_core.sv
Labels: Type:Bug, Component:RTL, Component:OTBN

#9245 [dv] Fix shape calculations for replicated ECC
  hw/dv/sv/mem_bkdr_util/mem_bkdr_util.sv
  hw/ip/otbn/dv/uvm/tb.sv
Labels: Component:DV, Type:Enhancement

#9256 [dv] Tweak name of run_stress_*_with_rand_reset_vseq
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
Labels: Component:DV, Type:Cleanup

#9240 [reggen] This adds initial support for a cm list
  util/reggen/countermeasure.py
  util/reggen/ip_block.py
Labels: Component:Doc, Component:Tooling

#9268 [prim] Fix prim_packer_fifo when ClearOnRead is false
  hw/ip/prim/rtl/prim_packer_fifo.sv
Labels: Type:Bug, Component:RTL

#9162 [sw/ottf] Reduce the size of the FreeRTOS heap.
  sw/device/lib/testing/test_framework/FreeRTOSConfig.h
  sw/device/lib/testing/test_framework/freertos_hooks.c
  sw/device/lib/testing/test_framework/freertos_hooks.h
Labels: Component:SW, Type:Cleanup

#9247 [otbn,sw] Combine input and output buffers for RSA code
  sw/device/silicon_creator/lib/sigverify_mod_exp_otbn.c
  sw/device/silicon_creator/otbn/rsa.s
  sw/device/tests/otbn_rsa_test.c
  sw/otbn/code-snippets/rsa.s
Labels: Component:SW, Type:Enhancement, Component:OTBN

#9263 [otbn,sw] A system-level OTBN test that waits by IRQ, not polling
  sw/device/tests/meson.build
  sw/device/tests/otbn_irq_test.c
  test/systemtest/earlgrey/config.py
Labels: Component:DV, Type:Enhancement, Component:OTBN

#9255 [sw] Clean up mtvec load code
  sw/device/exts/common/flash_crt.S
  sw/device/silicon_creator/rom_ext/rom_ext_start.S
  sw/device/silicon_owner/bare_metal/bare_metal_start.S
Labels: Component:SW

#9318 [sw/ottf] Fix typos in example OTTF test names.
  sw/device/tests/meson.build
Labels: Component:SW, Type:Cleanup

#8892 [otbn,util] Halve the DMEM region in OTBN's linker script
  hw/ip/otbn/data/otbn.ld.tpl
  sw/device/silicon_creator/otbn/rsa.s
  sw/otbn/crypto/rsa.s
  util/otbn_build.py
Labels: Component:Tooling, Type:Enhancement, Component:OTBN

#8895 [otbn,rtl] Narrow bus-visible DMEM to 2KiB
  hw/ip/otbn/data/otbn.hjson
  hw/ip/otbn/data/otbn.ld.tpl
  hw/ip/otbn/dv/otbnsim/sim/dmem.py
  hw/ip/otbn/dv/rig/rig/rig.py
  hw/ip/otbn/dv/verilator/otbn_top_sim.sv
  hw/ip/otbn/rtl/otbn.sv
  hw/ip/otbn/rtl/otbn_reg_pkg.sv
  hw/ip/otbn/rtl/otbn_reg_top.sv
  hw/ip/otbn/util/otbn-ld
Labels: Type:Enhancement, Component:RTL, Component:OTBN

#9138 [sw, tests] Refactor sram_ctrl scramble test and test utils
  sw/device/lib/testing/meson.build
  sw/device/lib/testing/sram_ctrl_testutils.c
  sw/device/lib/testing/sram_ctrl_testutils.h
  sw/device/tests/sram_ctrl_execution_test_main.c
  sw/device/tests/sram_ctrl_scrambled_access_test.c
Labels: Component:SW

#9239 [sw/ottf] Make FreeRTOS heap a NOLOAD section.
  sw/device/exts/common/flash_link.ld
  sw/device/lib/testing/test_framework/FreeRTOSConfig.h
  sw/device/lib/testing/test_framework/freertos_port.c
Labels: Component:SW

#9317 [sw/exts] Skip zero-ing stack in testing 2nd boot stage.
  sw/device/exts/common/flash_crt.S
Labels: Component:SW, Type:Cleanup

#9371 [sw/silicon_creator] Minor cleanups to shutdown code.
  sw/device/silicon_creator/lib/shutdown.c
  sw/device/silicon_creator/lib/shutdown_unittest.cc
Labels: Component:Mask ROM

#9316 [sw/test_rom] Skip SRAM request for new key and LFSR init in test ROM.
  hw/top_englishbreakfast/util/sw_sources.patch
  sw/device/boot_rom/rom_crt.S
Labels: Component:SW, Type:Cleanup

#9304 [dv] Allow using memutil_dpi_scrambled even without prim_ram_1p_scr
  hw/dv/verilator/cpp/scrambled_ecc32_mem_area.cc
Labels: Component:DV, Type:Enhancement

#9389 [mubi] Fix path in auto-gen header
  hw/ip/prim/prim_mubi.core
  hw/ip/prim/rtl/prim_mubi12_dec.sv
  hw/ip/prim/rtl/prim_mubi12_sender.sv
  hw/ip/prim/rtl/prim_mubi12_sync.sv
  hw/ip/prim/rtl/prim_mubi16_dec.sv
  hw/ip/prim/rtl/prim_mubi16_sender.sv
  hw/ip/prim/rtl/prim_mubi16_sync.sv
  hw/ip/prim/rtl/prim_mubi4_dec.sv
  hw/ip/prim/rtl/prim_mubi4_sender.sv
  hw/ip/prim/rtl/prim_mubi4_sync.sv
  hw/ip/prim/rtl/prim_mubi8_dec.sv
  hw/ip/prim/rtl/prim_mubi8_sender.sv
  hw/ip/prim/rtl/prim_mubi8_sync.sv
  hw/ip/prim/rtl/prim_mubi_pkg.sv
  util/design/data/prim_mubi.core.tpl
  util/design/data/prim_mubi_dec.sv.tpl
  util/design/data/prim_mubi_pkg.sv.tpl
  util/design/data/prim_mubi_sender.sv.tpl
  util/design/data/prim_mubi_sync.sv.tpl
Labels: Component:Tooling, Type:Cleanup

#9386 [rom_ctrl,doc] Document planned security countermeasures
  hw/ip/rom_ctrl/doc/_index.md
  hw/ip/rom_ctrl/doc/checklist.md
Labels: Component:Doc, Type:Enhancement

#9355 [otbn,python] Wrap code to 79 columns
  hw/ip/otbn/.flake8
  hw/ip/otbn/dv/otbnsim/sim/gpr.py
  hw/ip/otbn/dv/otbnsim/sim/state.py
  hw/ip/otbn/dv/otbnsim/sim/stats.py
  hw/ip/otbn/dv/otbnsim/sim/wsr.py
  hw/ip/otbn/dv/otbnsim/stepped.py
  hw/ip/otbn/dv/otbnsim/test/simple_test.py
  hw/ip/otbn/dv/otbnsim/test/stats_test.py
  hw/ip/otbn/dv/rig/rig/config.py
  hw/ip/otbn/dv/rig/rig/gens/bad_deep_loop.py
  hw/ip/otbn/dv/rig/rig/gens/bad_ispr.py
  hw/ip/otbn/dv/rig/rig/gens/bad_load_store.py
  hw/ip/otbn/dv/rig/rig/gens/branch.py
  hw/ip/otbn/dv/rig/rig/gens/branch_gen.py
  hw/ip/otbn/dv/rig/rig/gens/call_stack_rw.py
  hw/ip/otbn/dv/rig/rig/gens/edge_load_store.py
  hw/ip/otbn/dv/rig/rig/gens/known_wdr.py
  hw/ip/otbn/dv/rig/rig/gens/loop.py
  hw/ip/otbn/dv/rig/rig/gens/misaligned_load_store.py
  hw/ip/otbn/dv/rig/rig/gens/small_val.py
  hw/ip/otbn/dv/rig/rig/gens/straight_line_insn.py
  hw/ip/otbn/dv/rig/rig/gens/untaken_branch.py
  hw/ip/otbn/dv/rig/rig/init_data.py
  hw/ip/otbn/dv/rig/rig/known_mem.py
  hw/ip/otbn/dv/rig/rig/model.py
  hw/ip/otbn/dv/rig/rig/program.py
  hw/ip/otbn/dv/verilator/run-some.py
  hw/ip/otbn/util/shared/encoding.py
  hw/ip/otbn/util/shared/encoding_scheme.py
  hw/ip/otbn/util/shared/lsu_desc.py
  hw/ip/otbn/util/shared/operand.py
  hw/ip/otbn/util/shared/toolchain.py
  hw/ip/otbn/util/yaml_to_doc.py
  hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv
Labels: Component:DV, Component:Tooling, Type:Cleanup, Component:OTBN

#9319 [lc_ctrl] Make the life cycle state CSR multibit
  hw/ip/lc_ctrl/data/lc_ctrl.hjson
  hw/ip/lc_ctrl/dv/env/lc_ctrl_scoreboard.sv
  hw/ip/lc_ctrl/dv/env/seq_lib/lc_ctrl_base_vseq.sv
  hw/ip/lc_ctrl/rtl/lc_ctrl.sv
  hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv
  hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
  hw/ip/lc_ctrl/rtl/lc_ctrl_reg_top.sv
  hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
  hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv.tpl
  hw/ip/lc_ctrl/rtl/lc_ctrl_state_transition.sv
  sw/device/lib/dif/dif_lc_ctrl.c
  sw/device/lib/dif/dif_lc_ctrl_unittest.cc
  sw/device/silicon_creator/lib/drivers/lifecycle.h
Labels: Component:RTL, Component:Security

#9392 [rom_ctrl] Mark rom_ctrl as D2
  hw/ip/rom_ctrl/data/rom_ctrl.prj.hjson
Labels: Component:RTL

#9246 [dv] Teach encrypt/decrypt_sram_data to support OTBN
  hw/dv/sv/mem_bkdr_util/mem_bkdr_util__sram.sv
  hw/dv/sv/mem_bkdr_util/sram_scrambler_pkg.sv
  hw/ip/otbn/dv/uvm/env/otbn_env_cfg.sv
Labels: Component:DV, Type:Enhancement

#9393 [rom_ctrl] Correctly wire up fatal alerts from bus integrity errors
  hw/ip/rom_ctrl/rtl/rom_ctrl.sv
Labels: Type:Bug, Component:RTL
