Repository lowRISC/opentitan, pull requests merged in 2022-12, with the labels that each got.

#16623 [test] increase coremark test timeout
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
Labels: Type:Cleanup, Milestone:V3, Component:ChipLevelTest

#16621 [test] Add rom_e2e_default_otp_bootup test
  sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
  sw/device/silicon_creator/rom/e2e/BUILD
Labels: Status:Ready to merge, Component:Rom/E2e/Test

#16652 [top_earlgrey/dv] Fix quotes in `pre_build_cmds`
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
Labels: Component:DV, TOP:earlgrey

#16659 [ci,dv] run more tests in private CI with Xcelium
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
Labels: Component:DV, Priority:P1, Component:CI

#16680 [dv] Remove echo statement that causes issues in regressions
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
Labels: Priority:P0

#16676 [dv/cov] Exclude coverage of dv-only code
  hw/ip/flash_ctrl/rtl/flash_ctrl_lcmgr.sv
  hw/ip/flash_ctrl/rtl/flash_phy_rd_buf_dep.sv
  hw/ip/prim/rtl/prim_count.sv
  hw/ip/prim/rtl/prim_edn_req.sv
  hw/ip/prim/rtl/prim_max_tree.sv
  hw/ip/prim/rtl/prim_sum_tree.sv
  hw/ip/pwrmgr/rtl/pwrmgr.sv
  hw/ip/tlul/rtl/tlul_adapter_host.sv
Labels: Component:DV

#16679 [dv] Fix freq constraint
  hw/dv/sv/cip_lib/cip_base_env_cfg.sv
Labels: Component:DV

#16631 [test] Add tests for bitstream cache pagination-handling
  rules/scripts/bitstreams_workspace_test.py
Labels: Component:Tooling

#16697 [doc] Update i2c documentation.
  hw/ip/i2c/doc/_index.md
Labels: Component:Doc

#16704 [test] Fix testplan for rom_e2e_default_otp_bootup test
  sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
Labels: Type:Bug, Component:Rom/E2e/Task

#16714 [dv/kmac] Fix regression error
  hw/ip/kmac/dv/env/seq_lib/kmac_base_vseq.sv
Labels: IP:kmac

#16701 Add util/fpga/bitstream_bisect.py
  rules/scripts/BUILD
  rules/scripts/bitstreams_workspace.py
  rules/scripts/bitstreams_workspace_test.py
  util/fpga/BUILD
  util/fpga/bitstream_bisect.py
  util/fpga/bitstream_bisect_test.py
Labels: Component:FPGA, Component:Tooling, Status:Ready to merge

#16273 [ci] Move SW Build and Test job to ci-public
  azure-pipelines.yml
Labels: Component:CI

#16780 [opentitantool] Add TPM subcommand
  sw/host/opentitanlib/BUILD
  sw/host/opentitanlib/src/lib.rs
  sw/host/opentitanlib/src/tpm/driver.rs
  sw/host/opentitanlib/src/tpm/mod.rs
  sw/host/opentitantool/BUILD
  sw/host/opentitantool/src/command/i2c.rs
  sw/host/opentitantool/src/command/mod.rs
  sw/host/opentitantool/src/command/spi.rs
  sw/host/opentitantool/src/command/tpm.rs
Labels: Component:Software, SW:opentitantool

#16785 [hw,dv,chip] Increase timeout for random power glitch test
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_random_power_glitch_vseq.sv
Labels: Status:Ready to merge

#16774 [opentitantool] Add --delay flag to no-op command
  sw/host/opentitantool/src/command/mod.rs
Labels: Component:Software, SW:opentitantool

#16829 [ci] Disable the Verilator weak straps tests in CI
  ci/scripts/run-verilator-tests.sh
Labels: Component:CI, Status:Ready to merge, Component:Rom/E2e/Task

#16813 [ci] Initialize a nightly CI pipeline
  ci/azure-pipelines-nightly.yml
Labels: Component:CI, Component:Rom/E2e/Task

#16823 [ci] Allow logs to print when bitstream build fails
  azure-pipelines.yml
Labels: Component:CI, Status:Ready to merge

#16893 [bazel,doc,util] Update @bitstreams repository with Git hook
  doc/getting_started/setup_fpga.md
  rules/bitstreams.bzl
  util/git/hooks/post-checkout
Labels: Type:Bug, SW:Build System

#16807 [docs] update descriptions to point to .elf files for debug
  doc/getting_started/build_sw.md
  doc/getting_started/setup_fpga.md
Labels: Status:Ready to merge

#16895 [ci] Force pipeline to print logs even on Vivado failure
  azure-pipelines.yml
Labels: Component:CI, Status:Ready to merge

#16847 [lint,tlul] Resolve width error raised by Verilator lint
  hw/ip/tlul/rtl/tlul_sram_byte.sv
Labels: IP:tlul, Status:Ready to merge

#16802 [cryptolib, kmac] Connect SHA-3 to cryptolib's hash API
  sw/device/lib/crypto/drivers/BUILD
  sw/device/lib/crypto/drivers/kmac.c
  sw/device/lib/crypto/drivers/kmac.h
  sw/device/lib/crypto/drivers/kmac_test.c
  sw/device/lib/crypto/impl/BUILD
  sw/device/lib/crypto/impl/hash.c
  sw/device/lib/crypto/include/hash.h
Labels: SW:cryptolib

#16900 [ci] Configure nightly tests on public CI
  ci/azure-pipelines-nightly.yml
Labels: Component:CI, Component:Rom/E2e/Task

#16912 [util] Batch "git skip" in bitstream_bisect.py
  util/fpga/bitstream_bisect.py
  util/fpga/bitstream_bisect_test.py
Labels: Type:Enhancement

#16923 [test] configure UARTs and I2Cs in power virus test
  sw/device/tests/BUILD
  sw/device/tests/power_virus_systemtest.c
Labels: Component:ChipLevelTest

#16932 [bazel] //hw/bitstream:otp_mmi is testonly
  hw/bitstream/BUILD
Labels: Status:Ready to merge

#16915 [bazel] allocate additional core per verilator test to allow for harness and overhead
  .bazelrc
  rules/opentitan_test.bzl
Labels: Status:Ready to merge
