Repository lowRISC/opentitan, pull requests merged in 2022-10, with the labels that each got.

#15150 [doc] Update motivation and objectives of DIFs in RM
  doc/rm/device_interface_functions.md
Labels: Component:Doc

#15224 [sram_ctrl_ret] Tie off debug enable
  hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
  hw/top_earlgrey/data/top_earlgrey.hjson
  hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
Labels: Component:RTL

#15250 [dv,tests] add example concurrency test to DV smoke regression
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
Labels: Component:DV, Priority:P1, Milestone:V2, SW:OTTF

#15183 [PWRMGR|RSTMGR|ESC_ALERT] ESC domain separated from LC domain as requ…
  hw/dv/sv/pwrmgr_clk_ctrl_agent/pwrmgr_clk_ctrl_agent_cfg.sv
  hw/dv/sv/pwrmgr_clk_ctrl_agent/pwrmgr_clk_ctrl_monitor.sv
  hw/ip/pwrmgr/data/pwrmgr.hjson
  hw/ip/pwrmgr/data/pwrmgr.hjson.tpl
  hw/ip/pwrmgr/dv/env/pwrmgr_env.sv
  hw/ip/pwrmgr/dv/env/pwrmgr_env_cfg.sv
  hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_base_vseq.sv
  hw/ip/pwrmgr/dv/env/seq_lib/pwrmgr_esc_clk_rst_malfunc_vseq.sv
  hw/ip/pwrmgr/dv/sva/pwrmgr_bind.sv
  hw/ip/pwrmgr/dv/sva/pwrmgr_sec_cm_checker_assert.sv
  hw/ip/pwrmgr/dv/tb.sv
  hw/ip/pwrmgr/rtl/pwrmgr.sv
  hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
  hw/top_earlgrey/data/top_earlgrey.hjson
  hw/top_earlgrey/formal/conn_csvs/clkmgr_cg_en.csv
  hw/top_earlgrey/formal/conn_csvs/rstmgr_resets_o.csv
  hw/top_earlgrey/formal/conn_csvs/rstmgr_rst_en.csv
  hw/top_earlgrey/ip/pwrmgr/data/autogen/pwrmgr.hjson
  hw/top_earlgrey/ip_autogen/alert_handler/data/alert_handler.hjson
  hw/top_earlgrey/ip_autogen/alert_handler/data/top_earlgrey_alert_handler.ipconfig.hjson
  hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_reg_pkg.sv
  hw/top_earlgrey/lint/top_earlgrey.waiver
  hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
  hw/top_englishbreakfast/data/top_englishbreakfast.hjson
Labels: Status:Ready to merge

#15290 [cleanup] Fix merge skew
  sw/host/opentitantool/src/command/fpga_reset.rs
Labels: Priority:P0

#15213 [tests] Update life-cycle broadcast testpoint
  hw/top_earlgrey/data/chip_testplan.hjson
Labels: Component:DV

#15281 [dv] add several Xcelium regressions to scale up presubmit testing
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
Labels: Component:DV, Priority:P1, Type:Enhancement, Component:CI

#15306 [bazel] Update success pattern for sram_program_fpga_cw310_test
  sw/device/examples/sram_program/BUILD
Labels: Status:Ready to merge

#15375 [util] Fix compile_commands.json for git worktrees
  util/generate_compilation_db.py
  util/generate_compilation_db_test.py
Labels: Component:Software, Type:Bug, Status:Ready to merge

#15376 [otbn,dv] TP update for unmapped countermeasures
  hw/ip/otbn/data/otbn_sec_cm_testplan.hjson
Labels: Component:DV, IP:otbn, Milestone:V2S

#15369 [edn] Use MuBi4False instead of 4'h0 for flag0 when enabling entropy src
  sw/device/lib/dif/dif_csrng_shared.c
  sw/device/lib/dif/dif_csrng_unittest.cc
  sw/device/lib/dif/dif_edn_unittest.cc
  sw/device/lib/testing/entropy_testutils.c
Labels: Component:Software, Status:Ready to merge

#15383 [bazel] Update and fix typo in buildifier patch
  third_party/lint/0001-enable-buildifier-test-without-sandbox.patch
Labels: Component:Tooling, Status:Ready to merge

#15221 [top/dv] Add test glitching outputs of Ibex or lockstep core
  hw/top_earlgrey/data/chip_testplan.hjson
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
  hw/top_earlgrey/dv/env/chip_env.core
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_rv_core_ibex_lockstep_glitch.sv
  hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
Labels: Component:DV, IP:rv_core_ibex, Status:Ready to merge

#15417 [usbdev] Stub out logic in top_englishbreakfast
  hw/ip/usbdev/data/usbdev.hjson
  hw/ip/usbdev/rtl/usbdev.sv
  hw/ip/usbdev/usbdev.core
  hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
  hw/top_earlgrey/rtl/autogen/top_earlgrey.sv
  util/topgen/templates/chiplevel.sv.tpl
Labels: Priority:P0, IP:usbdev, TOP:englishbreakfast

#15456 [ottf] hide FreeRTOS internals from concurrency API
  sw/device/lib/testing/test_framework/ottf_main.h
Labels: Component:Software, Priority:P2, Type:Cleanup, Milestone:V2, SW:OTTF

#15454 [ci] add Xcelium DV test set 1 to private CI
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
Labels: Component:DV, Priority:P1, Type:Enhancement, Component:CI, Milestone:V2

#15464 [test_rom] enable icache / Ibex security features
  sw/device/lib/testing/test_rom/test_rom.c
Labels: Component:Software, Priority:P1, Type:Enhancement, SW:ROM

#15438 [otbn,doc] Add missing *fatal error* transition from init to locked
  hw/ip/otbn/doc/otbn_operational_states.svg
Labels: Component:Doc, IP:otbn, Status:Ready to merge

#15479 [otbn,dv] Add test for RF integrity error FIs
  hw/ip/otbn/data/otbn_sec_cm_testplan.hjson
  hw/ip/otbn/dv/tracer/rtl/otbn_trace_if.sv
  hw/ip/otbn/dv/uvm/env/otbn_env.core
  hw/ip/otbn/dv/uvm/env/otbn_rf_base_if.sv
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_intg_err_vseq.sv
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_base_intg_err_vseq.sv
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_rf_bignum_intg_err_vseq.sv
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_vseq_list.sv
  hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson
Labels: Component:DV, Type:Enhancement, IP:otbn, Milestone:V2S

#15466 [ci] add Xcelium DV test set 2 to private CI
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
Labels: Component:DV, Priority:P1, Type:Enhancement, Component:CI, Milestone:V2

#15555 Move dependabot configuration file into .github folder
  .github/dependabot.yml
Labels: Component:Tooling, Priority:P2

#15446 [bazel] update rules_rust to enable bindgen
  third_party/rust/deps.bzl
  third_party/rust/repos.bzl
  util/prep-bazel-airgapped-build.sh
Labels: Component:Software, Component:Tooling, Priority:P1, Type:Bug, SW:Build System

#15571 [top/dv] Adjust setup for floating pin.
  sw/device/lib/testing/pinmux_testutils.c
Labels: kokoro:rebuild

#15407 [otp/bazel] Refactor OTP Bazel rules and add overlay support
  hw/ip/otp_ctrl/data/BUILD
  rules/otp.bzl
Labels: Component:Tooling, IP:otp_ctrl

#15617 [sw] Invalidate icache in SRAM GDB test
  sw/device/examples/sram_program/BUILD
  sw/device/examples/sram_program/sram_program.c
Labels: Status:Ready to merge

#15626 [rv_dm] Move debug memory definitions into rv_dm.hjson
  hw/ip/rv_dm/data/rv_dm.hjson
  hw/ip/rv_dm/data/rv_dm_debug_mem.hjson
  hw/ip/rv_dm/dv/env/rv_dm_env.core
  hw/ip/rv_dm/dv/env/rv_dm_env_cfg.sv
  hw/ip/rv_dm/dv/env/rv_dm_env_pkg.sv
  hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
  hw/ip/rv_dm/dv/tb.sv
  hw/ip/rv_dm/lint/rv_dm.waiver
  hw/ip/rv_dm/rtl/rv_dm.sv
  hw/ip/rv_dm/rtl/rv_dm_mem_reg_top.sv
  hw/ip/rv_dm/rtl/rv_dm_reg_pkg.sv
  hw/ip/rv_dm/rv_dm.core
  hw/top_earlgrey/dv/env/chip_env.core
  hw/top_earlgrey/dv/env/chip_env_cfg.sv
  hw/top_earlgrey/dv/env/chip_env_pkg.sv
  hw/top_earlgrey/dv/env/chip_if.sv
Labels: IP:rv_dm

#15594 [test] Add test for SYSRST CTRL to detect input change
  hw/top_earlgrey/data/chip_testplan.hjson
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
  hw/top_earlgrey/dv/env/chip_env.core
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_in_irq_vseq.sv
  hw/top_earlgrey/dv/env/seq_lib/chip_vseq_list.sv
  sw/device/lib/dif/dif_sysrst_ctrl.h
  sw/device/tests/sim_dv/BUILD
  sw/device/tests/sim_dv/sysrst_ctrl_in_irq_test.c
Labels: Status:Ready to merge

#15603 [bitstream cache] Handle pagination when querying for all bitstreams
  rules/scripts/bitstreams_workspace.py
Labels: Component:Tooling, Type:Bug, Status:Ready to merge

#15653 [bazel] Rewrite GDB test script, respect subprocess exit codes
  rules/opentitan_gdb_test.bzl
  rules/scripts/BUILD
  rules/scripts/gdb_test_coordinator.py
Labels: Status:Ready to merge

#15699 [alert_handler] Increase chance that pinged alert ID is valid
  hw/ip_templates/alert_handler/rtl/alert_handler_ping_timer.sv
  hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv
Labels: IP:alert_handler

#15623 [bazel] Allow opentitan_functest to accept custom bitstreams
  rules/opentitan_test.bzl
Labels: Component:Tooling, SW:Build System

#15767 [rv_dm] Add generated registers to docs
  hw/ip/rv_dm/data/rv_dm.hjson
  hw/ip/rv_dm/doc/_index.md
  hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
Labels: IP:rv_dm

#15756 [test] Run GDB in batch mode so errors are fatal
  rules/scripts/gdb_test_coordinator.py
Labels: Component:Software, Type:Bug

#15797 [ci] rollback airgapped build test script changes in #15775
  ci/scripts/test-airgapped-build.sh
Labels: Priority:P0, Component:CI

#15784 [bazel] Unconditionally add tests to opentitan_functest test suites
  rules/opentitan_test.bzl
Labels: Status:Ready to merge

#15761 [bazel] Set hello_world example visibility to public
  sw/device/examples/hello_world/BUILD
Labels: Status:Ready to merge

#15812 [dv] remove unfinished tests from nightly dashboard
  sw/device/silicon_creator/rom/data/rom_e2e_testplan.hjson
Labels: Component:DV, Type:Cleanup

#15717 [top-level,test] add initial power virus test boilerplate
  sw/device/tests/BUILD
  sw/device/tests/power_virus_systemtest.c
Labels: Priority:P1, Milestone:V2, Component:ChipLevelTest

#15831 [bazel] rollback #15817 again
  third_party/rust/deps.bzl
  util/prep-bazel-airgapped-build.sh
Labels: Component:Tooling, Priority:P0, SW:Build System

#15758 [bitstream] Use the hash of the bitstream as the usr_access value
  sw/host/opentitanlib/src/util/usr_access.rs
  sw/host/opentitantool/src/command/update_usr_access.rs
Labels: Component:Tooling, SW:Build System, Component:Rom/E2e/Task

#15843 [dvsim] fix bindgen error in nightlies
  hw/dv/tools/dvsim/sim.mk
  third_party/rust/deps.bzl
  util/prep-bazel-airgapped-build.sh
Labels: Component:Tooling, Priority:P0, Type:Bug, SW:Build System

#15807 [bazel] enhance airgapped test to build more targets
  ci/scripts/test-airgapped-build.sh
  rules/scripts/bitstreams_workspace.py
Labels: Component:Tooling, Priority:P1, Type:Bug, Component:CI
