Repository lowRISC/opentitan, pull requests merged in 2023-11, with the labels that each got.

#20317 [otbn,doc] Extract list of ISRs into YAML files
  hw/ip/otbn/README.md
  hw/ip/otbn/data/csr.yml
  hw/ip/otbn/data/wsr.yml
  hw/ip/otbn/util/Makefile
  hw/ip/otbn/util/docs/md_isrs.py
  hw/ip/otbn/util/shared/isr.py
Labels: Component:Doc, Component:Tooling, IP:otbn

#20238 [sca] Add AES PRNG for aes-fvsr-key-batch capture
  sw/device/sca/BUILD
  sw/device/sca/aes_serial.c
  sw/device/sca/lib/BUILD
  sw/device/sca/lib/aes.c
  sw/device/sca/lib/aes.h
Labels: Status:Ready to merge

#20378 [top_darjeeling] Change SOC base address of JTAG Mbx to 0x800
  hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
  hw/top_darjeeling/data/top_darjeeling.hjson
  hw/top_darjeeling/dv/autogen/xbar_env_pkg__params.sv
  hw/top_darjeeling/dv/autogen/xbar_tgl_excl.cfg
  hw/top_darjeeling/ip/xbar_dbg/data/autogen/xbar_dbg.gen.hjson
  hw/top_darjeeling/ip/xbar_dbg/dv/autogen/xbar_cover.cfg
  hw/top_darjeeling/ip/xbar_dbg/dv/autogen/xbar_env_pkg__params.sv
  hw/top_darjeeling/ip/xbar_dbg/rtl/autogen/tl_dbg_pkg.sv
Labels: Component:Darjeeling

#20342 [util/topgen] Dynamic chip_info section generation
  hw/top_darjeeling/sw/autogen/top_darjeeling_memory.ld
  hw/top_earlgrey/sw/autogen/top_earlgrey_memory.ld
  sw/device/silicon_creator/rom/e2e/rom_e2e_self_hash_test.c
  sw/device/silicon_creator/rom/rom.ld
  util/topgen/templates/toplevel_memory.ld.tpl
Labels: Component:Darjeeling

#20445 [dv,mbx] Changes for vcs support
  hw/ip/mbx/dv/env/mbx_env_cfg.sv
  hw/ip/mbx/dv/env/mbx_env_pkg.sv
  hw/ip/mbx/dv/env/seq_lib/mbx_base_vseq.sv
  hw/ip/mbx/dv/tb.sv
Labels: Component:Darjeeling

#20444 [keymgr_dpe, rtl] Fix key switching during erase
  hw/ip/keymgr_dpe/rtl/keymgr_dpe_ctrl.sv
Labels: Component:Darjeeling

#20464 [csrng,dv] Simplify RAL access in csrng_scoreboard.sv
  hw/ip/csrng/dv/env/csrng_scoreboard.sv
Labels: Component:DV, Type:Cleanup, IP:csrng

#20470 [keymgr_dpe, rtl] Fix invalid data on invalid advance
  hw/ip/keymgr_dpe/rtl/keymgr_dpe.sv
  hw/ip/keymgr_dpe/rtl/keymgr_dpe_ctrl.sv
Labels: Component:Darjeeling

#20482 [top_darjeeling] Move JTAG mailbox to 0x1000
  hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
  hw/top_darjeeling/data/top_darjeeling.hjson
  hw/top_darjeeling/dv/autogen/xbar_env_pkg__params.sv
  hw/top_darjeeling/dv/autogen/xbar_tgl_excl.cfg
  hw/top_darjeeling/ip/xbar_dbg/data/autogen/xbar_dbg.gen.hjson
  hw/top_darjeeling/ip/xbar_dbg/dv/autogen/xbar_cover.cfg
  hw/top_darjeeling/ip/xbar_dbg/dv/autogen/xbar_env_pkg__params.sv
  hw/top_darjeeling/ip/xbar_dbg/rtl/autogen/tl_dbg_pkg.sv
Labels: Component:Darjeeling

#20479 [hw,dma,rtl] Fix enable signal for sys_req_.read_be
  hw/ip/dma/rtl/dma.sv
Labels: Component:Darjeeling

#19261 [adc_ctrl,dv] Fix adc_ctrl_lowpower_counter_vseq if used with resets
  hw/ip/adc_ctrl/dv/env/seq_lib/adc_ctrl_lowpower_counter_vseq.sv
Labels: Component:DV, IP:adc_ctrl

#20455 [hw,dma,rtl] Use cached opcode instead of unlocked register value
  hw/ip/dma/rtl/dma.sv
Labels: Component:Darjeeling

#20499 [hw,dma,rtl] Use the FSM state to lock/unlock the register set
  hw/ip/dma/data/dma.hjson
  hw/ip/dma/rtl/dma.sv
  hw/ip/dma/rtl/dma_reg_pkg.sv
  hw/ip/dma/rtl/dma_reg_top.sv
Labels: Component:Darjeeling

#20494 [hw,spi_host,dif] Split the configuration and FIFO read in different functions
  sw/ip/spi_host/dif/dif_spi_host.c
  sw/ip/spi_host/dif/dif_spi_host.h
  sw/ip/spi_host/dif/dif_spi_host_unittest.cc
Labels: Component:Darjeeling

#20446 [dv,csr] Support non-HRO REGWEN fields
  util/reggen/fpv_csr.sv.tpl
Labels: Component:Darjeeling
