Repository lowRISC/opentitan, pull requests merged in 2023-12, with the labels that each got.

#20570 [darjeeling,mbx/dv] Create scaffold for testplan
  hw/ip/mbx/data/mbx_testplan.hjson
Labels: Component:DV, Component:Darjeeling

#20484 [opentitantool] Add ability to "transport init" with strap
  sw/host/opentitanlib/src/app/mod.rs
  sw/host/opentitanlib/src/proxy/handler.rs
  sw/host/opentitanlib/src/proxy/mod.rs
  sw/host/opentitanlib/src/proxy/protocol.rs
  sw/host/opentitanlib/src/test_utils/init.rs
  sw/host/opentitanlib/src/transport/mod.rs
  sw/host/opentitanlib/src/transport/proxy/mod.rs
  sw/host/opentitantool/src/command/transport.rs
  sw/host/tests/manuf/manuf_cp_device_info_flash_wr/src/main.rs
  sw/host/tests/manuf/provisioning/ft/src/main.rs
Labels: SW:opentitantool

#20598 [dma] Report bus errors from 'clear int' writes
  hw/ip/dma/rtl/dma.sv
Labels: Component:Darjeeling

#20488 [hw/ip] otp_ctrl_mmap: Add a creator manufacturing overrides bucket
  hw/ip/otp_ctrl/data/otp_ctrl.hjson
  hw/ip/otp_ctrl/data/otp_ctrl_mmap.hjson
  hw/ip/otp_ctrl/doc/otp_ctrl_mmap.md
  hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv
  hw/ip/otp_ctrl/rtl/otp_ctrl_reg_pkg.sv
  hw/top_darjeeling/ip/ast/data/ast.hjson
  hw/top_darjeeling/ip/ast/rtl/ast.sv
  hw/top_darjeeling/ip/ast/rtl/ast_pkg.sv
  hw/top_darjeeling/ip/ast/rtl/ast_reg_pkg.sv
  hw/top_darjeeling/ip/ast/rtl/ast_reg_top.sv
  hw/top_earlgrey/ip/ast/data/ast.hjson
  hw/top_earlgrey/ip/ast/rtl/ast.sv
  hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv
  hw/top_earlgrey/ip/ast/rtl/ast_reg_pkg.sv
  hw/top_earlgrey/ip/ast/rtl/ast_reg_top.sv
Labels: Component:Darjeeling

#20463 [prim,cov] Fix type of sample_cov in prim_onehot_check_if
  hw/dv/sv/sec_cm/prim_onehot_check_if.sv
Labels: Component:DV

#20642 [dma] Src and dst alignment may differ
  hw/ip/dma/dv/env/dma_seq_item.sv
  hw/ip/dma/rtl/dma.sv
Labels: Component:Darjeeling

#20655 [dma] Fix for signaling of memory buffer (almost) limit interrupt
  hw/ip/dma/rtl/dma.sv
Labels: Component:Darjeeling

#20665 [doc] Fix path in setup_formal.md
  doc/getting_started/setup_formal.md
Labels: Component:Doc, Type:Cleanup

#20666 [util,formal] Make sure to fail in Make if a command dies
  hw/formal/tools/dvsim/formal.mk
Labels: Component:DV, Component:Tooling, Tool:dvsim

#20663 [util,fpvgen] Minor tidyup in parsing
  util/fpvgen/sv_parse.py
Labels: Component:DV, Component:Tooling

#20638 [sca] Move trigger source select to own uJSON command
  sw/device/tests/crypto/cryptotest/firmware/BUILD
  sw/device/tests/crypto/cryptotest/firmware/aes_sca.c
  sw/device/tests/crypto/cryptotest/firmware/firmware.c
  sw/device/tests/crypto/cryptotest/firmware/trigger_sca.c
  sw/device/tests/crypto/cryptotest/firmware/trigger_sca.h
  sw/device/tests/crypto/cryptotest/json/BUILD
  sw/device/tests/crypto/cryptotest/json/aes_sca_commands.h
  sw/device/tests/crypto/cryptotest/json/commands.h
  sw/device/tests/crypto/cryptotest/json/trigger_sca_commands.c
  sw/device/tests/crypto/cryptotest/json/trigger_sca_commands.h
Labels: Status:Ready to merge

#20659 [hw,mbx,rtl] Use the transition to the Read/Abort to generate the IRQ
  hw/ip/mbx/rtl/mbx_fsm.sv
Labels: Component:Darjeeling

#20563 [sca] KMAC uJSON handler
  sw/device/tests/crypto/cryptotest/firmware/BUILD
  sw/device/tests/crypto/cryptotest/firmware/firmware.c
  sw/device/tests/crypto/cryptotest/firmware/kmac_sca.c
  sw/device/tests/crypto/cryptotest/firmware/kmac_sca.h
  sw/device/tests/crypto/cryptotest/json/BUILD
  sw/device/tests/crypto/cryptotest/json/commands.h
  sw/device/tests/crypto/cryptotest/json/kmac_sca_commands.c
  sw/device/tests/crypto/cryptotest/json/kmac_sca_commands.h
Labels: Status:Ready to merge

#20593 [sca] SHA3 uJSON handler
  sw/device/tests/crypto/cryptotest/firmware/BUILD
  sw/device/tests/crypto/cryptotest/firmware/firmware.c
  sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
  sw/device/tests/crypto/cryptotest/firmware/sha3_sca.h
  sw/device/tests/crypto/cryptotest/json/BUILD
  sw/device/tests/crypto/cryptotest/json/commands.h
  sw/device/tests/crypto/cryptotest/json/sha3_sca_commands.c
  sw/device/tests/crypto/cryptotest/json/sha3_sca_commands.h
Labels: Status:Ready to merge

#20662 [util] Fix minor nits in fpvgen Python script
  util/fpvgen.py
Labels: Component:DV, Component:Tooling
