Repository lowRISC/opentitan, pull requests merged in 2023-10, with the labels that each got.

#19736 [opentitantool] Refactor cw310 json files
  rules/scripts/gdb_test_coordinator.py
  sw/host/opentitanlib/src/app/config/cw340.json
  sw/host/opentitanlib/src/app/config/mod.rs
  sw/host/opentitanlib/src/app/config/opentitan.json
  sw/host/opentitanlib/src/app/config/opentitan_cw310.json
  sw/host/opentitanlib/src/app/config/opentitan_cw340.json
  sw/host/opentitanlib/src/app/gpio.rs
  sw/host/opentitanlib/src/transport/chip_whisperer/mod.rs
  sw/host/opentitanlib/src/transport/chip_whisperer/spi.rs
Labels: SW:opentitantool

#19992 [ci] Avoiding timeout in "CW310 ROM Tests"
  azure-pipelines.yml
Labels: Component:CI

#19947 [opentitantool] Move SPI pin declaration from Rust into json
  sw/host/opentitanlib/src/app/config/opentitan_cw310.json
  sw/host/opentitanlib/src/app/config/opentitan_cw340.json
  sw/host/opentitanlib/src/app/mod.rs
  sw/host/opentitanlib/src/transport/chip_whisperer/board.rs
  sw/host/opentitanlib/src/transport/chip_whisperer/gpio.rs
  sw/host/opentitanlib/src/transport/chip_whisperer/spi.rs
Labels: SW:opentitantool

#19944 [opentitantool] Do not specify OpenOCD ports
  sw/host/opentitanlib/src/io/jtag.rs
  sw/host/opentitanlib/src/util/openocd.rs
Labels: SW:opentitantool

#20036 [util] Error out if secure_prng seed is less than 256 bits
  util/design/gen-otp-img.py
  util/design/lib/LcStEnc.py
  util/design/lib/OtpMemImg.py
  util/design/lib/OtpMemMap.py
  util/design/lib/common.py
  util/dvsim/Deploy.py
  util/dvsim/dvsim.py
  util/topgen.py
  util/topgen/secure_prng.py
Labels: Status:Ready to merge

#19785 [prim_prince] Split an array in the RTL
  hw/ip/prim/lint/prim_cipher.vlt
  hw/ip/prim/rtl/prim_prince.sv
Labels: Component:RTL

#19610 [otbn,dv] Make "dirty" flag more selective in otbnsim ext_regs.py
  hw/ip/otbn/dv/otbnsim/sim/ext_regs.py
Labels: Component:DV, IP:otbn
