Repository lowRISC/opentitan, pull requests merged in 2023-03, with the labels that each got.

#17420 [cdc] Fix cdc waiver path
  hw/top_earlgrey/cdc/cdc_waivers.w_masync.tcl
Labels: IP:lc_ctrl, IP:rv_dm, Component:CDC

#17283 [opentitantool] Propagate `transport init` to backend
  WORKSPACE
  sw/host/opentitanlib/src/app/mod.rs
  sw/host/opentitanlib/src/proxy/handler.rs
  sw/host/opentitanlib/src/proxy/protocol.rs
  sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
  sw/host/opentitanlib/src/transport/mod.rs
  sw/host/opentitanlib/src/transport/proxy/mod.rs
Labels: SW:opentitantool

#17270 [cargo]: Repin crates, and add Cargo.lock to git
  .gitignore
  third_party/rust/Cargo.lock
  third_party/rust/crates/BUILD.addr2line-0.19.0.bazel
  third_party/rust/crates/BUILD.bazel
  third_party/rust/crates/BUILD.cxx-1.0.91.bazel
  third_party/rust/crates/BUILD.cxx-build-1.0.91.bazel
  third_party/rust/crates/BUILD.cxxbridge-flags-1.0.91.bazel
  third_party/rust/crates/BUILD.cxxbridge-macro-1.0.91.bazel
  third_party/rust/crates/BUILD.fastrand-1.9.0.bazel
  third_party/rust/crates/BUILD.gimli-0.27.2.bazel
  third_party/rust/crates/BUILD.iana-time-zone-haiku-0.1.1.bazel
  third_party/rust/crates/BUILD.once_cell-1.17.1.bazel
  third_party/rust/crates/BUILD.pest_meta-2.5.5.bazel
  third_party/rust/crates/BUILD.proc-macro-crate-1.3.0.bazel
  third_party/rust/crates/BUILD.serde_json-1.0.93.bazel
  third_party/rust/crates/BUILD.tempfile-3.3.0.bazel
  third_party/rust/crates/BUILD.typetag-0.1.8.bazel
  third_party/rust/crates/BUILD.wasm-bindgen-backend-0.2.84.bazel
  third_party/rust/crates/defs.bzl
Labels: SW:opentitantool

#17290 [doc,sysrst_ctrl] Change debounce register descriptions
  hw/ip/sysrst_ctrl/data/sysrst_ctrl.hjson
Labels: Component:Doc, IP:sysrst_ctrl, Status:Ready to merge

#13168 [opentitanlib] Add rust_doc target
  sw/host/opentitanlib/BUILD
Labels: Component:Doc, Component:Software, SW:opentitantool

#17443 [flash_ctrl] fix incorrect `IPoly` parameter in flash scrambler
  hw/dv/sv/mem_bkdr_util/mem_bkdr_util__flash.sv
  hw/ip/flash_ctrl/dv/env/flash_ctrl_env_pkg.sv
  hw/ip/flash_ctrl/rtl/flash_phy_pkg.sv
  hw/ip/flash_ctrl/rtl/flash_phy_scramble.sv
Labels: Priority:P1, Type:Bug, Component:RTL, IP:flash_ctrl

#17439 [i2c,doc] Update DV page simulation results link
  hw/dv/doc/dv_doc_template.md
  hw/ip/i2c/dv/README.md
  hw/ip/otbn/dv/README.md
  hw/ip/sram_ctrl/dv/README.md
  hw/ip_templates/alert_handler/dv/README.md
  hw/top_earlgrey/dv/README.md
  hw/top_earlgrey/ip_autogen/alert_handler/dv/README.md
  util/uvmdvgen/index.md.tpl
Labels: Component:Doc, Status:Ready to merge

#17272 [opentitantool] Add EEPROM primitives to SPI trait
  sw/host/opentitanlib/BUILD
  sw/host/opentitanlib/src/io/eeprom.rs
  sw/host/opentitanlib/src/io/mod.rs
  sw/host/opentitanlib/src/io/spi.rs
  sw/host/opentitanlib/src/spiflash/flash.rs
Labels: SW:opentitantool

#17432 [opentitantool]: Proxy forwarding of strappings
  sw/host/opentitanlib/src/app/mod.rs
  sw/host/opentitanlib/src/proxy/handler.rs
  sw/host/opentitanlib/src/proxy/protocol.rs
  sw/host/opentitanlib/src/transport/mod.rs
  sw/host/opentitanlib/src/transport/proxy/mod.rs
Labels: SW:opentitantool

#17470 [dv/kmac] Add assertion cov exclusion
  hw/ip/keymgr/dv/cov/keymgr_cov_excl.el
Labels: Status:Ready to merge

#17504 [dv/chip] Add an independent task set and release sw_strap_pins
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
Labels: Status:Ready to merge

#17516 [bazel,dvsim] enable passing `--data-perm` flag through dvsim/bazel
  hw/dv/tools/dvsim/sim.mk
  hw/ip/otp_ctrl/data/BUILD
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
  rules/otp.bzl
Labels: Component:Tooling, Priority:P1, Type:Enhancement, SW:Build System

#17498 [util,bazel] integrate flash scrambling with bazel
  rules/opentitan.bzl
  rules/opentitan_test.bzl
  sw/device/tests/BUILD
  util/design/BUILD
  util/design/gen-flash-img.py
Labels: Component:Tooling, Type:Enhancement, SW:Build System

#17562 [pinmux,testutils] only configure SW strap pins input selection
  sw/device/lib/testing/pinmux_testutils.c
Labels: Component:Software, Type:Cleanup

#17551 [earlgrey/dv] Remove outdated TODO comment
  hw/top_earlgrey/dv/chip_smoketests.hjson
Labels: Component:DV, TOP:earlgrey

#17442 [hw,i2c] Add support for Xcelium
  hw/ip/i2c/dv/env/seq_lib/i2c_base_vseq.sv
  hw/ip/i2c/dv/env/seq_lib/i2c_target_smoke_vseq.sv
Labels: Component:DV, IP:i2c

#17560 [util] compute flash scrambling keys in flash VMEM processing script
  util/design/gen-flash-img.py
Labels: Component:Software, Component:Tooling, Priority:P1

#17505 [opentitantool] Stricter validation of HyperDebug responses
  sw/host/opentitanlib/src/transport/hyperdebug/gpio.rs
Labels: SW:opentitantool

#17514 [opentitantool] HyperDebug: Dynamic I2C port discovery
  WORKSPACE
  sw/host/opentitanlib/src/transport/hyperdebug/c2d2.rs
  sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs
  sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
  sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
Labels: SW:opentitantool

#17564 [hw,i2c] Add missing entries in testplan
  hw/ip/i2c/data/i2c_testplan.hjson
  hw/ip/i2c/dv/i2c_sim_cfg.hjson
Labels: Component:DV, IP:i2c

#17512 [opentitantool] Consider interface field in conf files
  sw/host/opentitanlib/src/app/mod.rs
  sw/host/opentitanlib/src/backend/mod.rs
  sw/host/opentitanlib/src/transport/errors.rs
Labels: SW:opentitantool

#17515 [opentitantool] Allow sending/receiving plain bytes via SPI
  sw/host/opentitantool/src/command/spi.rs
Labels: SW:opentitantool

#17607 [test] fix power virus test
  sw/device/tests/power_virus_systemtest.c
Labels: Type:Bug, Type:Cleanup, Component:ChipLevelTest

#17584 [ottool] Add a `raw-write-read` command for I2C
  sw/host/opentitantool/src/command/i2c.rs
Labels: SW:opentitantool

#17502 [otbn/sca] Improve OTBN SCA capture setup
  sw/device/sca/ecc256_keygen_serial.c
Labels: Status:Ready to merge

#17636 [opentitantool] Only do UART pacing when SW flow control enabled
  sw/host/opentitanlib/src/transport/common/uart.rs
Labels: SW:opentitantool

#17631 [opentitantool] Gpio monitoring via proxy
  sw/host/opentitanlib/src/proxy/handler.rs
  sw/host/opentitanlib/src/proxy/protocol.rs
  sw/host/opentitanlib/src/transport/proxy/gpio.rs
  sw/host/opentitanlib/src/transport/proxy/mod.rs
Labels: SW:opentitantool

#17716 [dv/tl_agent] Add function to determine data written by TL item
  hw/dv/sv/tl_agent/tl_seq_item.sv
Labels: Component:DV

#17718 [entropy_src/dv] Fixes for VCS compatibility
  hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
  hw/ip/entropy_src/dv/tests/entropy_src_functional_errors_test.sv
Labels: Component:DV, IP:entropy_src

#17611 [top_earlgrey/dv] Add testpoint for `spi_device` outputs when disabled or sleeping
  hw/top_earlgrey/data/chip_testplan.hjson
Labels: Component:DV, IP:pinmux, IP:spi_device, TOP:earlgrey

#17738 [dv/chip] Add testunlock to strap test
  hw/top_earlgrey/data/chip_testplan.hjson
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
Labels: Status:Ready to merge

#17753 [dv/otp_ctrl] Enhance OTP lc esc sequence
  hw/ip/otp_ctrl/dv/env/seq_lib/otp_ctrl_parallel_lc_esc_vseq.sv
Labels: Status:Ready to merge
