Repository lowRISC/opentitan, pull requests merged in 2023-08, with the labels that each got.

#19330 [tlgen] Remove an ancient "error" debug print
  util/tlgen/doc.py
Labels: Type:Cleanup, Component:CI

#19349 [ci] Actually build all software in the sw_build job
  azure-pipelines.yml
Labels: Component:CI

#17836 Disable ccache under Bazel
  .bazelrc
Labels: SW:Build System

#19408 [otbn,dv] Wrap some secure wipe assertions in a named block
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv
  hw/ip/otbn/rtl/otbn.sv
Labels: Component:DV, IP:otbn

#19280 [pwrmgr,dv] Correct name of disabled assertion
  hw/ip/pwrmgr/dv/env/pwrmgr_if.sv
Labels: Component:DV, IP:pwrmgr

#19436 [otbn,dv] Delay "start" signal for OTBN in pre-DV code by a cycle
  hw/ip/otbn/dv/verilator/otbn_top_sim.sv
Labels: Component:DV, IP:otbn

#18625 [rom/doc] Typo fix
  sw/device/silicon_creator/rom/doc/e2e_tests.md
Labels: Status:Ready to merge

#19509 [doc] Add CW340 to 'Get an FPGA Board' page
  doc/contributing/fpga/get_a_board.md
Labels: Component:Doc

#19395 [otbn,dv] Add a "safe" mode to RIG; use it in otbn_ctrl_redun test
  hw/ip/otbn/dv/rig/rig/configs/safe.yml
  hw/ip/otbn/dv/uvm/gen-binaries.py
  hw/ip/otbn/dv/uvm/otbn_sim_cfg.hjson
Labels: Component:DV, IP:otbn

#19529 [opentitantool] Include updated HyperDebug firmware
  third_party/hyperdebug/repos.bzl
Labels: SW:opentitantool

#19530 [opentitantool] Tolerate non-writeable /var/lock
  sw/host/opentitanlib/src/transport/common/uart.rs
Labels: SW:opentitantool
