Repository lowRISC/opentitan, pull requests merged in 2023-09, with the labels that each got.

#19562 [dv] Iterate over a shorter list of CSRs in shadow reg errors test
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh
Labels: Component:DV

#19570 [opentitantool] Allow configuration of I2C address
  sw/host/opentitanlib/src/app/config/hyperdebug_cw310.json
  sw/host/opentitanlib/src/app/config/structs.rs
  sw/host/opentitanlib/src/app/mod.rs
  sw/host/opentitanlib/src/io/i2c.rs
  sw/host/opentitanlib/src/proxy/protocol.rs
  sw/host/opentitanlib/src/tpm/driver.rs
  sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs
  sw/host/opentitanlib/src/transport/ioexpander/sx1503.rs
  sw/host/opentitanlib/src/transport/proxy/i2c.rs
  sw/host/opentitanlib/src/transport/ti50emulator/i2c.rs
  sw/host/opentitantool/src/command/i2c.rs
  sw/host/tests/chip/i2c_target/src/main.rs
  sw/host/tpm2_test_server/src/main.rs
Labels: SW:opentitantool

#19385 [otbn,dv] Strengthen otbn_ctrl_redun_vseq
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv
Labels: Component:DV, IP:otbn

#19405 [dv,c] Ensure strdup() is defined when compiling tcp_server.c
  hw/dv/dpi/common/tcp_server/tcp_server.c
Labels: Component:Software, Type:Cleanup

#19235 [alert_handler,dv] Tweak clocking block used in wait_alert_init_done
  hw/dv/sv/alert_esc_agent/alert_monitor.sv
Labels: Component:DV, IP:alert_handler

#19645 [opentitantool] Updated HyperDebug firmware
  third_party/hyperdebug/repos.bzl
Labels: SW:opentitantool

#19638 [opentitantool] Recognize CMSIS-DAP HyperDebug USB interface
  sw/host/opentitanlib/src/transport/hyperdebug/i2c.rs
  sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
Labels: SW:opentitantool

#19621 [opentitantool] Work around lack of bidirectional SPI
  sw/host/opentitanlib/src/app/mod.rs
  sw/host/opentitanlib/src/io/spi.rs
  sw/host/opentitanlib/src/proxy/handler.rs
  sw/host/opentitanlib/src/proxy/protocol.rs
  sw/host/opentitanlib/src/tpm/driver.rs
  sw/host/opentitanlib/src/transport/chip_whisperer/spi.rs
  sw/host/opentitanlib/src/transport/dediprog/spi.rs
  sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
  sw/host/opentitanlib/src/transport/proxy/spi.rs
  sw/host/opentitanlib/src/transport/ti50emulator/spi.rs
  sw/host/opentitanlib/src/transport/ultradebug/spi.rs
Labels: SW:opentitantool

#19612 [otbn,dv] Rewrite a line more efficiently in wsr.py
  hw/ip/otbn/dv/otbnsim/sim/wsr.py
Labels: Component:DV, IP:otbn

#19563 [clkmgr,dv] Avoid passing a mubi4_t as a uvm_reg_data_t output arg
  hw/ip/clkmgr/dv/env/seq_lib/clkmgr_regwen_vseq.sv
Labels: Component:DV, IP:clkmgr

#19616 [otbn,dv] Make types slightly cleaner in ext_regs.py
  hw/ip/otbn/dv/otbnsim/sim/ext_regs.py
Labels: Component:DV, Type:Cleanup, IP:otbn

#19641 [doc] Fixing a few typos in xoshiro PRNG documentation
  hw/ip/prim/doc/prim_xoshiro256pp.md
Labels: Status:Ready to merge

#19667 [opentitantool] Support inverted GPIO sense
  sw/host/opentitanlib/BUILD
  sw/host/opentitanlib/src/app/config/structs.rs
  sw/host/opentitanlib/src/app/gpio.rs
  sw/host/opentitanlib/src/app/mod.rs
  sw/host/opentitanlib/src/transport/errors.rs
Labels: SW:opentitantool

#19706 [opentitantool] Yet another fix to legacy Titan rescue protocol
  sw/host/opentitanlib/src/bootstrap/rescue.rs
Labels: SW:opentitantool

#19709 [ci] only use pinned python packages
  ci/install-package-dependencies.sh
  python-requirements.in
  python-requirements.txt
Labels: kokoro:rebuild

#19666 [opentitantool] Allow config control of all spi pins
  sw/host/opentitanlib/src/app/config/structs.rs
  sw/host/opentitanlib/src/app/mod.rs
  sw/host/opentitanlib/src/app/spi.rs
  sw/host/opentitanlib/src/io/spi.rs
  sw/host/opentitanlib/src/proxy/handler.rs
  sw/host/opentitanlib/src/proxy/protocol.rs
  sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
  sw/host/opentitanlib/src/transport/proxy/spi.rs
Labels: SW:opentitantool

#19618 [otbn,dv] Cleanups of wsr.py in otbnsim
  hw/ip/otbn/dv/otbnsim/sim/wsr.py
Labels: Component:DV, IP:otbn

#19759 [opentitantool] Wrapper cleanup
  sw/host/opentitanlib/src/app/mod.rs
Labels: SW:opentitantool

#19773 [opentitantool] Handle writing of large amounts of UART data
  sw/host/opentitanlib/src/transport/common/uart.rs
Labels: SW:opentitantool
