Repository lowRISC/opentitan, pull requests merged in 2024-09, with the labels that each got.

#24295 [pentest] Add Crypto FI tests
  sw/device/tests/penetrationtests/firmware/BUILD
  sw/device/tests/penetrationtests/firmware/fi/BUILD
  sw/device/tests/penetrationtests/firmware/fi/crypto_fi.c
  sw/device/tests/penetrationtests/firmware/fi/crypto_fi.h
  sw/device/tests/penetrationtests/firmware/firmware.c
  sw/device/tests/penetrationtests/firmware/firmware_fi.c
  sw/device/tests/penetrationtests/json/BUILD
  sw/device/tests/penetrationtests/json/commands.h
  sw/device/tests/penetrationtests/json/crypto_fi_commands.c
  sw/device/tests/penetrationtests/json/crypto_fi_commands.h
Labels: Status:Ready to merge

#24296 [pentest] Add ROM FI tests
  sw/device/tests/penetrationtests/firmware/BUILD
  sw/device/tests/penetrationtests/firmware/fi/BUILD
  sw/device/tests/penetrationtests/firmware/fi/rom_fi.c
  sw/device/tests/penetrationtests/firmware/fi/rom_fi.h
  sw/device/tests/penetrationtests/firmware/firmware.c
  sw/device/tests/penetrationtests/firmware/firmware_fi.c
  sw/device/tests/penetrationtests/json/BUILD
  sw/device/tests/penetrationtests/json/commands.h
  sw/device/tests/penetrationtests/json/rom_fi_commands.c
  sw/device/tests/penetrationtests/json/rom_fi_commands.h
Labels: Status:Ready to merge

#24298 [pentest] Add LC_CTRL FI tests
  sw/device/tests/penetrationtests/firmware/BUILD
  sw/device/tests/penetrationtests/firmware/fi/BUILD
  sw/device/tests/penetrationtests/firmware/fi/lc_ctrl_fi.c
  sw/device/tests/penetrationtests/firmware/fi/lc_ctrl_fi.h
  sw/device/tests/penetrationtests/firmware/firmware.c
  sw/device/tests/penetrationtests/firmware/firmware_fi.c
  sw/device/tests/penetrationtests/json/BUILD
  sw/device/tests/penetrationtests/json/commands.h
  sw/device/tests/penetrationtests/json/lc_ctrl_fi_commands.c
  sw/device/tests/penetrationtests/json/lc_ctrl_fi_commands.h
Labels: Status:Ready to merge

#24390 [pentest] Update and add new Ibex SCA tests
  sw/device/sca/lib/prng.c
  sw/device/sca/lib/prng.h
  sw/device/tests/penetrationtests/firmware/sca/BUILD
  sw/device/tests/penetrationtests/firmware/sca/ibex_sca.c
  sw/device/tests/penetrationtests/firmware/sca/ibex_sca.h
  sw/device/tests/penetrationtests/json/ibex_sca_commands.h
Labels: Status:Ready to merge

#24391 [pentest] Add HMAC SCA tests
  sw/device/tests/penetrationtests/firmware/BUILD
  sw/device/tests/penetrationtests/firmware/firmware.c
  sw/device/tests/penetrationtests/firmware/firmware_sca.c
  sw/device/tests/penetrationtests/firmware/sca/BUILD
  sw/device/tests/penetrationtests/firmware/sca/hmac_sca.c
  sw/device/tests/penetrationtests/firmware/sca/hmac_sca.h
  sw/device/tests/penetrationtests/json/BUILD
  sw/device/tests/penetrationtests/json/commands.h
  sw/device/tests/penetrationtests/json/hmac_sca_commands.c
  sw/device/tests/penetrationtests/json/hmac_sca_commands.h
Labels: Status:Ready to merge

#24297 [pentest] Add OTP FI tests
  sw/device/tests/penetrationtests/firmware/BUILD
  sw/device/tests/penetrationtests/firmware/fi/BUILD
  sw/device/tests/penetrationtests/firmware/fi/otp_fi.c
  sw/device/tests/penetrationtests/firmware/fi/otp_fi.h
  sw/device/tests/penetrationtests/firmware/firmware.c
  sw/device/tests/penetrationtests/firmware/firmware_fi.c
  sw/device/tests/penetrationtests/json/BUILD
  sw/device/tests/penetrationtests/json/commands.h
  sw/device/tests/penetrationtests/json/otp_fi_commands.c
  sw/device/tests/penetrationtests/json/otp_fi_commands.h
Labels: Status:Ready to merge

#24501 [earlgrey_1.0.0,spi_host/rtl] Fix `sd_en_o` of `spi_host_fsm`
  hw/ip/spi_host/rtl/spi_host_fsm.sv
Labels: ECO

#24531 [rv_dm,dv] Handle reset at surprising time in resuming vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_resuming_vseq.sv
Labels: Component:DV, IP:rv_dm

#24553 [rom, rom_ext] Enable pull-up on UART_RX
  sw/device/silicon_creator/lib/drivers/pinmux.c
  sw/device/silicon_creator/lib/drivers/pinmux_unittest.cc
Labels: CherryPick:master

#24562 [dv,vcs] Tidy up how coverage is collected in assertion modules
  hw/dv/tools/vcs/cover.cfg
  hw/dv/tools/vcs/cover_reg_top.cfg
  hw/ip/rv_dm/dv/cov/cover.cfg
  hw/ip/rv_dm/dv/cov/cover_reg_top.cfg
  hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
Labels: Component:DV, Component:Tooling

#24457 [i2c,dv] Add csr write excl to OVERRIDE csr
  hw/ip/i2c/data/i2c.hjson
Labels: Component:DV, IP:i2c

#24567 [rv_dm,dv] Manually waive line coverage for unreachable code
  hw/ip/rv_dm/dv/cov/rv_dm_cov_excl.el
Labels: Component:DV, IP:rv_dm

#24546 [pentest] Add EDN SCA tests
  sw/device/tests/penetrationtests/firmware/BUILD
  sw/device/tests/penetrationtests/firmware/fi/rng_fi.c
  sw/device/tests/penetrationtests/firmware/firmware.c
  sw/device/tests/penetrationtests/firmware/firmware_sca.c
  sw/device/tests/penetrationtests/firmware/sca/BUILD
  sw/device/tests/penetrationtests/firmware/sca/edn_sca.c
  sw/device/tests/penetrationtests/firmware/sca/edn_sca.h
  sw/device/tests/penetrationtests/json/BUILD
  sw/device/tests/penetrationtests/json/commands.h
  sw/device/tests/penetrationtests/json/edn_sca_commands.c
  sw/device/tests/penetrationtests/json/edn_sca_commands.h
Labels: Status:Ready to merge

#24491 [prim,fpv] Strengthen CntErrReported_A assertion in prim_count.sv
  hw/ip/prim/rtl/prim_count.sv
Labels: Component:FPV, IP:prim

#24494 [prim,fpv] Tweak DataKnown_A assertion in prim_fifo_sync.sv
  hw/ip/prim/rtl/prim_fifo_sync.sv
Labels: Component:FPV, IP:prim

#24454 [prim,fpv] Get rid of ASSERT_KNOWN in an FPV context
  hw/ip/prim/rtl/prim_assert.sv
  hw/ip/prim/rtl/prim_assert_standard_macros.svh
Labels: Component:FPV

#24463 [prim,fpv] Fix the bind statement in prim_alert_rxtx_fatal_bind_fpv
  hw/ip/prim/fpv/tb/prim_alert_rxtx_fatal_bind_fpv.sv
Labels: Component:FPV, IP:prim

#24271 [rv_dm,dv] Fix constant width in vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_halt_resume_whereto_vseq.sv
Labels: Component:DV, IP:rv_dm

#24346 [otbn,dv] Correct the timing for when we zero insn_cnt in model
  hw/ip/otbn/dv/otbnsim/sim/sim.py
  hw/ip/otbn/dv/otbnsim/sim/state.py
Labels: Component:DV, IP:otbn

#24586 [otp_ctrl/doc] Clarify documentation around MacroWriteBlankError
  hw/ip/otp_ctrl/doc/programmers_guide.md
Labels: ManuallyCherryPick:earlgrey_1.0.0

#24604 [top_earlgrey,pinmux] Enable pull-down for TAP strap 0 at reset
  hw/ip/pinmux/data/pinmux.hjson
  hw/ip/pinmux/data/pinmux.hjson.tpl
  hw/ip/pinmux/doc/registers.md
  hw/ip/pinmux/lint/pinmux.waiver
  hw/ip/pinmux/rtl/pinmux.sv
  hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
Labels: IP:pinmux, TOP:earlgrey

#24622 [clkmgr] Deglitch shadow storage error for MAIN clock domain
  hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv
  util/reggen/reg_top.sv.tpl
Labels: IP:clkmgr, ECO

#24632 [sw/tests] Add OTP descrambling test
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
  sw/device/tests/BUILD
  sw/device/tests/otp_ctrl_descrambling_test.c
Labels: IP:otp_ctrl

#24312 [hw,dma,rtl] Cleanup unused signals
  hw/ip/dma/rtl/dma.sv
Labels: Component:Darjeeling, IP:dma

#24490 [fpv,prim] Fix PrimCountFpv define in prim_count tests
  hw/top_earlgrey/formal/top_earlgrey_fpv_prim_cfgs.hjson
Labels: Component:FPV, IP:prim

#24670 [crypto] Let otcrypto_aes() have up to 3 blocks in flight
  sw/device/lib/crypto/impl/aes.c
Labels: CherryPick:earlgrey_es_sival

#24606 Excluded the continuous assignment block of rom_ctrl_scrambled_rom.sv…
  hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_excl.el
Labels: Component:DV, IP:rom_ctrl

#24675 [rv_dm] Assert development stage V2S
  hw/ip/rv_dm/data/rv_dm.hjson
Labels: Component:DV, IP:rv_dm

#24497 [prim,fpv] Remove initialisation before a test
  hw/ip/prim/rtl/prim_lfsr.sv
Labels: Component:FPV, IP:prim

#24679 [tlul,rtl] Modify readback check error reporting logic
  hw/ip/tlul/rtl/tlul_sram_byte.sv
Labels: Component:RTL, IP:sram_ctrl, IP:tlul, ManuallyCherryPick:earlgrey_1.0.0
