Repository lowRISC/opentitan, pull requests merged in 2024-05, with the labels that each got.

#22875 [topgen] Support for multiple rv_dm instances
  hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
  hw/top_darjeeling/data/top_darjeeling.hjson
  hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
  hw/top_earlgrey/data/top_earlgrey.hjson
  util/topgen/c_test.py
  util/topgen/merge.py
  util/topgen/validate.py
Labels: Component:Darjeeling

#22940 [rom_ext] temporarily disable cert updating
  sw/device/silicon_creator/rom_ext/rom_ext.c
Labels: kokoro:rebuild

#22950 [rom] Remove real and fake key targets.
  azure-pipelines.yml
  ci/scripts/test-airgapped-build.sh
  hw/bitstream/BUILD
  hw/bitstream/README.md
  hw/bitstream/cw340/BUILD
  hw/bitstream/hyperdebug/BUILD
  hw/dv/tools/dvsim/sim.mk
  hw/top_earlgrey/BUILD
  hw/top_earlgrey/dv/chip_rom_tests.hjson
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
  quality/BUILD.bazel
  release/BUILD
  sw/device/silicon_creator/manuf/lib/BUILD
  sw/device/silicon_creator/manuf/skus/earlgrey_a0/sival_bringup/BUILD
  sw/device/silicon_creator/manuf/tests/BUILD
  sw/device/silicon_creator/rom/BUILD
  sw/device/silicon_creator/rom/e2e/BUILD
  sw/device/silicon_creator/rom/e2e/boot_policy_valid/BUILD
  sw/device/silicon_creator/rom/e2e/epmp_init/BUILD
  sw/device/silicon_creator/rom/e2e/keymgr/BUILD
  sw/device/silicon_creator/rom/e2e/release/BUILD
  sw/device/silicon_creator/rom/e2e/shutdown_output/BUILD
  sw/device/silicon_creator/rom/e2e/sigverify_spx/BUILD
  sw/device/silicon_creator/rom/e2e/watchdog/BUILD
  sw/device/silicon_creator/rom/e2e/weak_straps/BUILD
  sw/device/tests/BUILD
  sw/device/tests/closed_source/BUILD.bazel
  sw/device/tests/doc/sival/devguide.md
  util/py/scripts/audit_sec_mmio_calls.py
  util/py/scripts/object_size.py
Labels: kokoro:rebuild

#22918 [sival,pwrmgr] Enable `pwrmgr_usbdev_smoketest` in sival
  hw/top_earlgrey/data/chip_testplan.hjson
  hw/top_earlgrey/dv/chip_smoketests.hjson
  sw/device/tests/BUILD
  sw/device/tests/pwrmgr_usbdev_smoketest.c
  sw/device/tests/sim_dv/BUILD
Labels: CherryPick:master

#22855 [alert_handler,dv] Disable an assertion that breaks for FI tests
  hw/ip_templates/alert_handler/dv/env/seq_lib/alert_handler_common_vseq.sv
  hw/top_earlgrey/ip_autogen/alert_handler/dv/env/seq_lib/alert_handler_common_vseq.sv
Labels: Component:DV, IP:alert_handler

#22937 [spi_device] Track intercept_en along the read pipeline
  hw/ip/spi_device/rtl/spi_device.sv
Labels: IP:spi_device

#22593 [rom] Avoid touching watchdog config on wake from sleep
  sw/device/silicon_creator/rom/rom.c
  sw/device/silicon_creator/rom/rom_start.S
Labels: SW:ROM

#22945 [rom_ext] Print fault info in the exception handler
  sw/device/silicon_creator/rom_ext/rom_ext.c
Labels: CherryPick:master

#22980 [prim_diff_decode] Use `prim_xnor2` to detect integrity issue
  hw/ip/prim/prim_diff_decode.core
  hw/ip/prim/rtl/prim_diff_decode.sv
Labels: Component:RTL, IP:prim

#22986 [prim_diff_decode] Use `prim_xnor2` to detect integrity issue
  hw/ip/prim/prim_diff_decode.core
  hw/ip/prim/rtl/prim_diff_decode.sv
Labels: Component:RTL, IP:prim, Component:Darjeeling

#22987 [keymgr,keymgr_dpe] Modify PRNG reseeding
  hw/ip/keymgr/data/keymgr.hjson
  hw/ip/keymgr/dv/env/keymgr_if.sv
  hw/ip/keymgr/dv/env/seq_lib/keymgr_base_vseq.sv
  hw/ip/keymgr/dv/tb.sv
  hw/ip/keymgr/rtl/keymgr.sv
  hw/ip/keymgr/rtl/keymgr_reseed_ctrl.sv
  hw/ip/keymgr_dpe/data/keymgr_dpe.hjson
  hw/ip/keymgr_dpe/dv/env/keymgr_dpe_if.sv
  hw/ip/keymgr_dpe/dv/env/seq_lib/keymgr_dpe_base_vseq.sv
  hw/ip/keymgr_dpe/dv/tb.sv
  hw/ip/keymgr_dpe/rtl/keymgr_dpe.sv
Labels: Component:RTL, IP:keymgr, Component:Darjeeling, IP:keymgr_dpe

#23005 [dv] Tweak tl_device_seq to avoid a runtime warning from Xcelium
  hw/dv/sv/tl_agent/seq_lib/tl_device_seq.sv
Labels: Component:DV, IP:tlul

#23012 [manuf] fix provisioning orchistrator
  sw/host/provisioning/cp/BUILD
  sw/host/provisioning/ft/BUILD
  sw/host/provisioning/orchestrator/orchestrator.py
  sw/host/provisioning/orchestrator/ot_device.py
Labels: CherryPick:master

#23016 [Sival, spi] Fix TPM test on teacup boad.
  sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
Labels: CherryPick:master

#23010 [rom_ext] fix cert update
  sw/device/silicon_creator/rom_ext/rom_ext.c
Labels: CherryPick:earlgrey_es_sival

#23015 [sival, testplan] Mark tests as NA for sival
  hw/top_earlgrey/data/chip_conn_testplan.hjson
  hw/top_earlgrey/data/ip/chip_csrng_testplan.hjson
  hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
  hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
  hw/top_earlgrey/data/ip/chip_lc_ctrl_testplan.hjson
Labels: CherryPick:master

#22828 [prim,fpv] Use PossibleActions param in prim_esc_receiver
  hw/ip/prim/rtl/prim_esc_receiver.sv
Labels: Component:FPV, IP:prim

#22829 [prim,rtl] Avoid unnecessary check in prim_esc_receiver.sv
  hw/ip/prim/rtl/prim_esc_receiver.sv
Labels: Component:RTL, IP:prim

#22999 [sival] Refactor testplans for consistency
  hw/top_earlgrey/data/ip/chip_adc_ctrl_testplan.hjson
  hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
  hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
  hw/top_earlgrey/data/ip/chip_aon_timer_testplan.hjson
  hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson
  hw/top_earlgrey/data/ip/chip_csrng_testplan.hjson
  hw/top_earlgrey/data/ip/chip_edn_testplan.hjson
  hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
  hw/top_earlgrey/data/ip/chip_flash_ctrl_testplan.hjson
  hw/top_earlgrey/data/ip/chip_gpio_testplan.hjson
  hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
  hw/top_earlgrey/data/ip/chip_i2c_testplan.hjson
  hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
  hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
  hw/top_earlgrey/data/ip/chip_lc_ctrl_testplan.hjson
  hw/top_earlgrey/data/ip/chip_otp_ctrl_testplan.hjson
  hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson
  hw/top_earlgrey/data/ip/chip_rom_ctrl_testplan.hjson
  hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
  hw/top_earlgrey/data/ip/chip_rv_timer_testplan.hjson
  hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
  hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
  hw/top_earlgrey/data/ip/chip_sram_ctrl_testplan.hjson
  hw/top_earlgrey/data/ip/chip_sysrst_ctrl_testplan.hjson
  hw/top_earlgrey/data/ip/chip_uart_testplan.hjson
  hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
Labels: CherryPick:master

#23035 [sival] Mark fixed entropy complex tests as unbroken in ROM_EXT
  sw/device/tests/BUILD
Labels: CherryPick:earlgrey_es_sival

#22594 [rv_dm,dv] Connect rst_lc_ni in tb.sv
  hw/ip/rv_dm/dv/env/rv_dm_env.sv
  hw/ip/rv_dm/dv/env/rv_dm_env_cfg.sv
  hw/ip/rv_dm/dv/tb.sv
Labels: Component:DV, IP:rv_dm

#22991 [sival,sram_ctrl] Fix SRAM execution test in ROM_EXT environments
  sw/device/tests/BUILD
  sw/device/tests/sram_ctrl_execution_test.c
Labels: CherryPick:master

#23056 [sival, spi_dev] Link spi_passthrough_collision in testplan
  hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
Labels: CherryPick:master

#22989 [sival,sram_ctrl] Fix scrambled_access ECC error counts
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_sram_ctrl_scrambled_access_vseq.sv
  sw/device/tests/sram_ctrl_scrambled_access_test.c
Labels: CherryPick:master

#22611 [otbn,dv] Improve error rate in `otbn_ctrl_redun_vseq`
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv
Labels: Component:DV, IP:otbn

#22893 [chip,dv] Wait for JTAG connection in chip_sw_base_vseq
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_base_vseq.sv
Labels: Component:ChipLevelTest

#23034 [flash_ctrl,dv] Remove bogus checks from flash_otf_item.sv
  hw/ip_templates/flash_ctrl/dv/env/flash_otf_item.sv
  hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/flash_otf_item.sv
Labels: Component:DV, IP:flash_ctrl

#23033 [flash_ctrl,dv] Correct macro names in flash_ctrl_phy_arb_redun_vseq
  hw/ip_templates/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv
  hw/top_earlgrey/ip_autogen/flash_ctrl/dv/env/seq_lib/flash_ctrl_phy_arb_redun_vseq.sv
Labels: Component:DV, IP:flash_ctrl

#23003 [rv_dm,dv] Rewrite dtm_idle_hint_vseq to use DMI helpers
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_idle_hint_vseq.sv
Labels: Component:DV, IP:rv_dm

#23047 [test] Make e2e_bootstrap_rma test more resilient
  sw/host/tests/rom/e2e_bootstrap_rma/src/main.rs
Labels: CherryPick:master

#23067 [spi_host] Disable FWFT for the command queue
  hw/ip/spi_host/rtl/spi_host_command_queue.sv
Labels: Component:RTL, IP:spi_host

#23062 [rescue] Send only the application firmware
  sw/host/opentitanlib/BUILD
  sw/host/opentitanlib/src/image/image.rs
  sw/host/opentitanlib/src/image/manifest.rs
  sw/host/opentitantool/src/command/image.rs
  sw/host/opentitantool/src/command/rescue.rs
Labels: CherryPick:master

#22596 [rv_dm,dv] Expose new ports in rv_dm_if
  hw/ip/rv_dm/dv/env/rv_dm_if.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
  hw/ip/rv_dm/dv/tb.sv
Labels: Component:DV, IP:rv_dm

#22876 [sival, rv_core_ibex] test rv_core_ibex_isa_test in prod
  hw/top_earlgrey/data/ip/chip_rv_core_ibex_testplan.hjson
  sw/device/tests/BUILD
  sw/device/tests/sival/BUILD
Labels: IP:rv_core_ibex, Component:SiliconValidation

#23054 [sival,pwrmgr] Add test harness for pwrmgr_deep_sleep_all_reset_reqs
  sw/device/tests/BUILD
Labels: CherryPick:master

#23042 [top_earlgrey,pinmux] Add input disable pad attribute
  hw/ip/pinmux/data/pinmux.hjson
  hw/ip/pinmux/data/pinmux.hjson.tpl
  hw/ip/pinmux/doc/registers.md
  hw/ip/pinmux/doc/theory_of_operation.md
  hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
  hw/ip/pinmux/rtl/pinmux.sv
  hw/ip/pinmux/rtl/pinmux_reg_pkg.sv
  hw/ip/pinmux/rtl/pinmux_reg_top.sv
  hw/ip/prim/rtl/prim_pad_wrapper_pkg.sv
  hw/ip/prim_generic/rtl/prim_generic_pad_attr.sv
  hw/ip/prim_generic/rtl/prim_generic_pad_wrapper.sv
  hw/ip/prim_xilinx/rtl/prim_xilinx_pad_attr.sv
  hw/ip/prim_xilinx/rtl/prim_xilinx_pad_wrapper.sv
  hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_pad_attr.sv
  hw/ip/prim_xilinx_ultrascale/rtl/prim_xilinx_ultrascale_pad_wrapper.sv
  hw/top_earlgrey/dv/env/seq_lib/chip_padctrl_attributes_vseq.sv
  hw/top_earlgrey/ip/pinmux/data/autogen/pinmux.hjson
  hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_pkg.sv
  hw/top_earlgrey/ip/pinmux/rtl/autogen/pinmux_reg_top.sv
  hw/top_earlgrey/rtl/padring.sv
  sw/device/lib/dif/dif_pinmux.c
  sw/device/lib/dif/dif_pinmux.h
  sw/device/lib/dif/dif_pinmux_unittest.cc
  sw/device/silicon_creator/rom/e2e/rom_e2e_c_init_test.c
Labels: Component:RTL, IP:pinmux, TOP:earlgrey

#23001 [keymgr, dv] Fix a typo in keymgr seq
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_keymgr_key_derivation_vseq.sv
Labels: Status:Ready to merge

#23046 [rv_dm,dv] Drive correct enable signal in dmi_disabled vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
Labels: Component:DV, IP:rv_dm

#23134 [rv_dm,dv] Add missing waits to rv_dm_jtag_dmi_debug_disabled_vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
Labels: Component:DV, IP:rv_dm

#23113 [jtag,dv] Mark driver internal state variables as protected
  hw/dv/sv/jtag_agent/jtag_driver.sv
Labels: Component:DV, IP:rv_dm

#23128 [usbdev,sival] Fix config_host and aon_pullup on silicon
  sw/device/tests/BUILD
Labels: CherryPick:master

#23127 [rom_ext] Communicate minimum security version in the boot_log
  sw/device/silicon_creator/lib/boot_log.h
  sw/device/silicon_creator/rom_ext/rom_ext.c
Labels: CherryPick:master

#23173 [signing] Remove the legacy `cloud_kms` token
  signing/README.md
  signing/tokens/BUILD
  sw/device/tests/doc/sival/README.md
Labels: CherryPick:master

#23177 [bufix] Correct a typo in the `mapfile_to_json` script.
  util/py/scripts/mapfile_to_json.py
Labels: CherryPick:earlgrey_es_sival

#23182 [rtl,rv_core_ibex] Mask off lower bits of mapping address
  hw/ip/rv_core_ibex/rtl/rv_core_addr_trans.sv
Labels: Component:Darjeeling

#23119 [opentitantool] Improvements for C2D2 debugger support
  sw/host/opentitanlib/src/app/config/h1dx_devboard_c2d2.json
Labels: SW:opentitantool, CherryPick:earlgrey_es_sival

#23172 [pinmux,fpv] Various tweaks to avoid lint warnings
  hw/ip/pinmux/fpv/vip/pinmux_assert_fpv.sv
Labels: Component:FPV, IP:pinmux

#23225 [top_earlgrey/dv] Create regression set for nightly Xcelium runs
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
Labels: Component:DV, TOP:earlgrey

#23218 Add bazel target to `chip_sw_sleep_pin_retention`
  hw/top_earlgrey/data/chip_testplan.hjson
Labels: CherryPick:master

#23247 [tool,fpvgen] Fix variable in fusesoc.core.tpl
  util/fpvgen/fusesoc.core.tpl
Labels: Component:Tooling

#23091 [rom_ext_e2e] Document ownership transfer testplan
  sw/device/silicon_creator/rom_ext/data/rom_ext_e2e_testplan.hjson
Labels: CherryPick:earlgrey_es_sival

#23233 [hmac/rtl] Fix idle_o when told to stop
  hw/ip/hmac/rtl/hmac.sv
  hw/ip/hmac/rtl/hmac_core.sv
Labels: Component:RTL, IP:hmac

#23167 [sival, rv_core_ibex] check for dbus address translation
  sw/device/tests/rv_core_ibex_address_translation_test.c
Labels: CherryPick:earlgrey_es_sival

#23227 [fpv] Tweak report headers to match Jasper version
  hw/formal/tools/jaspergold/parse-formal-report.py
  util/dvsim/FormalCfg.py
Labels: Type:Cleanup, Component:FPV

#23201 [top_earlgrey,padring] Implement muxing for IOB[0:3]
  hw/top_earlgrey/padring.core
  hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
  hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
  hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw340.sv
  hw/top_earlgrey/rtl/padring.sv
  util/topgen/templates/chiplevel.sv.tpl
Labels: TOP:earlgrey

#23244 [spi_device] Add CSB reset sync for outclk domain
  hw/ip/spi_device/lint/spi_device.waiver
  hw/ip/spi_device/lint/spi_tpm.waiver
  hw/ip/spi_device/rtl/spi_device.sv
  hw/ip/spi_device/rtl/spi_passthrough.sv
  hw/ip/spi_device/rtl/spi_readcmd.sv
  hw/ip/spi_device/rtl/spi_tpm.sv
  hw/ip/spi_device/rtl/spid_jedec.sv
  hw/ip/spi_device/rtl/spid_status.sv
Labels: Component:RTL, IP:spi_device

#23267 [rom_ext_e2e] Test the `MinBl0SecVer` request
  sw/device/silicon_creator/lib/error.h
  sw/device/silicon_creator/rom_ext/e2e/boot_svc/BUILD
  sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_min_sec_ver_test.c
  sw/device/silicon_creator/rom_ext/e2e/boot_svc/boot_svc_test_lib.h
  sw/device/silicon_creator/rom_ext/rom_ext.c
Labels: CherryPick:master

#23312 [top_earlgrey/dv] Fix timeout in `chip_sw_keymgr_key_derivation_vseq`
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_keymgr_key_derivation_vseq.sv
  sw/device/lib/testing/keymgr_testutils.c
Labels: Component:DV, TOP:earlgrey

#23273 [top_earlgrey,sensor_ctrl] Add pull attributes for manual pads
  hw/top_earlgrey/dv/env/seq_lib/chip_padctrl_attributes_vseq.sv
  hw/top_earlgrey/ip/sensor_ctrl/data/sensor_ctrl.hjson
  hw/top_earlgrey/ip/sensor_ctrl/doc/registers.md
  hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl.sv
  hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_reg_pkg.sv
  hw/top_earlgrey/ip/sensor_ctrl/rtl/sensor_ctrl_reg_top.sv
Labels: Component:RTL, TOP:earlgrey, IP:sensor_ctrl

#23327 [usbdev,sival] Make config_host test more reliable
  sw/device/tests/BUILD
Labels: CherryPick:master

#23285 [sival] otp_ctrl_smoketest cannot run after rom_ext
  sw/device/tests/BUILD
Labels: CherryPick:earlgrey_es_sival

#22369 [spi_host/doc]: Correct RST -> SW_RST typo
  hw/ip/spi_host/doc/theory_of_operation.md
Labels: Component:Doc, IP:spi_host

#23211 [cryptolib] Eliminate `status_create` symbol use
  sw/device/lib/crypto/drivers/entropy.c
Labels: CherryPick:earlgrey_es_sival

#23386 [silicon_creator] make rnd32 work at owner stage
  sw/device/silicon_creator/lib/drivers/BUILD
  sw/device/silicon_creator/lib/drivers/rnd.c
Labels: CherryPick:earlgrey_es_sival

#23368 [rv_dm,dv] Tidy-ups in the smoke vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_smoke_vseq.sv
Labels: Component:DV, IP:rv_dm

#23097 [jtag,dv] Improve driver sync with TCK
  hw/dv/sv/jtag_agent/jtag_driver.sv
Labels: Component:DV, IP:rv_dm

#23370 [prim,fpv] Avoid warning message from Jasper with ASSERT_AT_RESET
  hw/ip/prim/rtl/prim_assert_standard_macros.svh
Labels: Component:FPV

#23384 [kmac,prim_sha2/rtl] Fix lint error in endian conversion functions
  hw/ip/kmac/rtl/kmac_pkg.sv
  hw/ip/prim/rtl/prim_sha2_pkg.sv
Labels: Component:RTL, IP:kmac

#23106 [rv_dm,dv] Add a slight wait when enabling debug in rv_dm_base_vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
Labels: Component:DV, IP:rv_dm

#23375 [rv_dm,dv] Connect mon_jtag_if to internal signals
  hw/ip/rv_dm/dv/tb.sv
Labels: Component:DV, IP:rv_dm

#23379 [opentitantool] Updated HyperDebug firmware
  third_party/hyperdebug/repos.bzl
Labels: SW:opentitantool, CherryPick:earlgrey_es_sival

#20934 [opentitantool] Allow changing which pins to use for JTAG
  sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
  sw/host/opentitanlib/src/transport/mod.rs
  sw/host/opentitantool/src/command/transport.rs
Labels: SW:opentitantool, CherryPick:earlgrey_es_sival

#23397 [dv,jtag] Fix overflow in timeout calculation
  hw/dv/sv/jtag_dmi_agent/jtag_rv_debugger.sv
Labels: Component:DV

#23399 [rv_dm,dv] Increase (and justify) timeout for tests
  hw/ip/rv_dm/dv/tests/rv_dm_base_test.sv
Labels: Component:DV, IP:rv_dm

#23406 [rv_dm,dv] Increase the wait time for injecting resets
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_common_vseq.sv
Labels: Component:DV, IP:rv_dm

#23402 [opentitantool] Restore baud rate after rescue
  sw/host/opentitantool/src/command/rescue.rs
Labels: SW:opentitantool, CherryPick:earlgrey_es_sival
