Repository lowRISC/opentitan, pull requests merged in 2024-07, with the labels that each got.

#23843 [hmac,dv] Improve feature coverage
  hw/ip/hmac/dv/env/hmac_env_cov.sv
  hw/ip/hmac/dv/env/hmac_scoreboard.sv
  hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
Labels: Component:DV, IP:hmac

#23855 [hmac,dv] Increase SHA2 test vector timeout
  hw/ip/hmac/dv/hmac_sim_cfg.hjson
Labels: Component:DV, IP:hmac

#23852 [otbn,dv] Avoid killing during TL read in otbn_stack_addr_integ_chk
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_base_vseq.sv
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_stack_addr_integ_chk_vseq.sv
Labels: Component:DV, IP:otbn

#23749 [hmac,dv] FIFO empty interrupt and test mode pins
  hw/ip/hmac/dv/env/hmac_scoreboard.sv
Labels: Component:DV, IP:hmac

#23848 [hmac,dv] Optimize regression duration
  hw/ip/hmac/dv/env/seq_lib/hmac_stress_all_vseq.sv
  hw/ip/hmac/dv/hmac_sim_cfg.hjson
Labels: Component:DV, IP:hmac

#23858 [i2c,dv] Override agent sequence for target_tx_stretch_ctrl test
  hw/ip/i2c/dv/env/seq_lib/i2c_target_tx_stretch_ctrl_vseq.sv
Labels: Component:DV, IP:i2c

#23366 [rv_dm,dv] Widen exclusion for dmi register in jtag_dtm_reg_block
  hw/dv/sv/jtag_agent/jtag_dtm_reg_block.sv
Labels: Component:DV, IP:rv_dm

#23396 [dv] Minor tidy-up tweaks to tl_access_sub
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
Labels: Component:DV

#23865 [i2c,dv] Add write-check csr_excl for FMTFIFO/TXFIFO registers
  hw/ip/i2c/data/i2c.hjson
Labels: Component:DV, IP:i2c

#23857 [i2c,dv] Add csr test exclusions for CSR.{target,controller}_event
  hw/ip/i2c/data/i2c.hjson
Labels: Component:DV, IP:i2c

#23864 [hmac,dv] Fix msg_length coverage
  hw/ip/hmac/dv/env/hmac_env_cov.sv
Labels: Component:DV, IP:hmac

#23755 [rv_dm,dv] Avoid writing to command in rv_dm_jtag_dtm_idle_hint_vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dtm_idle_hint_vseq.sv
Labels: Component:DV, IP:rv_dm

#23793 [rv_dm,dv] Allow pinmux_hw_debug_en_i to be more independent
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
Labels: Component:DV, IP:rv_dm

#23887 [pinmux,fpv] Fix PinmuxTargetCfg initialiser in pinmux_tb.sv
  hw/ip/pinmux/fpv/pinmux_fpv.core
  hw/ip/pinmux/fpv/tb/pinmux_tb.sv
  hw/top_earlgrey/ip/pinmux/fpv/pinmux_chip_fpv.core
  hw/top_earlgrey/ip/pinmux/fpv/tb/pinmux_tb.sv
Labels: Component:FPV, IP:pinmux

#23796 [rv_dm,dv] Get rid of unnecessary re-randomisation in base vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
Labels: Component:DV, IP:rv_dm

#23841 [rv_dm,dv] Teach SVA and scoreboard about late debug enable
  hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
  hw/ip/rv_dm/dv/sva/rv_dm_bind.sv
  hw/ip/rv_dm/dv/sva/rv_dm_enable_checker.sv
Labels: Component:DV, IP:rv_dm

#23741 [rv_dm,dv] Add debug print to rv_dm_stress_all_vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_stress_all_vseq.sv
Labels: Component:DV, IP:rv_dm

#23885 [rv_core_ibex,dv] Fault lockstep enable signal
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_rv_core_ibex_lockstep_glitch_vseq.sv
Labels: Component:DV, IP:rv_core_ibex

#23901 [hmac,dv] Test msg_length_upper
  hw/ip/hmac/dv/env/seq_lib/hmac_base_vseq.sv
Labels: Component:DV, IP:hmac

#23886 [otbn,dv] Avoid null pointer dereference in otbn_scoreboard
  hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
Labels: Component:DV, IP:otbn

#23907 [otbn,dv] Try to improve model's support for RMA requests
  hw/ip/otbn/dv/otbnsim/sim/sim.py
Labels: Component:DV, IP:otbn

#23884 [otbn,dv] Fix a bug in random instruction generator
  hw/ip/otbn/dv/rig/rig/gens/bad_branch.py
Labels: Component:DV, IP:otbn

#23929 [sw/tests] Fix `rv_dm_access_after_wakeup` on FPGA
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_rv_dm_access_after_wakeup_vseq.sv
  sw/device/tests/rv_dm_access_after_wakeup.c
  sw/host/tests/chip/rv_dm/src/access_after_wakeup.rs
Labels: Component:FPGA, Component:Software

#23943 [top_earlgrey/dv] Fix `rom_raw_unlock` test
  hw/top_earlgrey/dv/chip_rom_tests.hjson
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_lc_raw_unlock_vseq.sv
Labels: Component:DV

#23945 [hmac/dv] Map tests to `fifo_empty_status_interrupt` testpoint
  hw/ip/hmac/data/hmac_testplan.hjson
Labels: Component:DV, IP:hmac

#23960 [otbn,lint] Fix silly Python lint error
  hw/ip/otbn/dv/otbnsim/sim/sim.py
Labels: Component:DV, IP:otbn

#23972 [rv_dm,dv] Correctly set pinmux_hw_debug_en_i in rv_dm_ndmreset_req
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
Labels: Component:DV, IP:rv_dm

#23973 [rv_dm,dv] Don't use late_debug_enable through a CSR if scb disabled
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
Labels: Component:DV, IP:rv_dm

#23968 [otbn,dv] Explicitly drop pending start request if we lock
  hw/ip/otbn/dv/uvm/env/otbn_scoreboard.sv
Labels: Component:DV, IP:otbn

#23995 [otbn,dv] Remove some stray debug prints
  hw/ip/otbn/dv/model/otbn_core_model.sv
  hw/ip/otbn/dv/otbnsim/sim/sim.py
Labels: Component:DV, IP:otbn

#23994 [otbn,dv] Wipe INSN_CNT on an RMA that comes in when we're wiping
  hw/ip/otbn/dv/otbnsim/sim/sim.py
Labels: Component:DV, IP:otbn

#23981 [rv_dm,dv] Use the "right enable" in *_jtag_dmi_debug_disabled_vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
Labels: Component:DV, IP:rv_dm

#24010 [i2v,dv] Move TP:target_error_intr / i2c_target_unexp_stop to V3
  hw/ip/i2c/data/i2c_testplan.hjson
Labels: Component:DV, IP:i2c

#24011 [i2c,dv] Move I2C to hardware development stage V2(S)
  hw/ip/i2c/data/i2c.hjson
Labels: Component:DV, IP:i2c, Type:Signoff

#24018 [hw/pulp_riscv_dbg] Fix reset value of `tap_state_q`
  hw/dv/sv/jtag_agent/jtag_agent_cfg.sv
  hw/dv/sv/jtag_agent/jtag_monitor.sv
  hw/ip/rv_dm/dv/env/rv_dm_env_cfg.sv
  hw/vendor/patches/pulp_riscv_dbg/0008-dmi_jtag_tap-fix-tap_state_q.patch
  hw/vendor/pulp_riscv_dbg/src/dmi_jtag_tap.sv
Labels: ECO

#24021 Update lowrisc_ibex to lowRISC/ibex@96a1c02b
  hw/vendor/lowrisc_ibex.lock.hjson
  hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/env/core_ibex_dut_probe_if.sv
  hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/riscv_dv_extension/testlist.yaml
  hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/tb/core_ibex_tb_top.sv
  hw/vendor/lowrisc_ibex/dv/uvm/core_ibex/tests/core_ibex_test_lib.sv
  hw/vendor/lowrisc_ibex/rtl/ibex_core.sv
Labels: ECO

#24029 [jtag,dv] Fix monitor tracking of trst_n
  hw/dv/sv/jtag_agent/jtag_monitor.sv
Labels: Component:DV, IP:rv_dm

#24032 [dv,jtag] Don't constrain wait for trst_n to be de-asserted
  hw/dv/sv/jtag_agent/jtag_driver.sv
Labels: Component:DV

#24037 [hmac,dv] Verify idle status register
  hw/ip/hmac/dv/env/hmac_scoreboard.sv
Labels: Component:DV, IP:hmac

#24033 [rv_dm,dv] Remove upper bound from trst_n wait
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
Labels: Component:DV, IP:rv_dm

#24044 [rv_dm,dv] Weaken enable checker to allow "left over" items
  hw/ip/rv_dm/dv/sva/rv_dm_enable_checker.sv
Labels: Component:DV, IP:rv_dm

#24065 [rv_dm,dv] Weaken IDCODE check
  hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
Labels: Component:DV, IP:rv_dm

#24083 [kmac,dv] Increase timeouts for some tests
  hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
Labels: Component:DV, IP:kmac

#24075 [dv] Add a quick exit in csr_rd_sub when in reset
  hw/dv/sv/csr_utils/csr_utils_pkg.sv
Labels: Component:DV

#24088 [kmac,dv] Increase timeout
  hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
Labels: Component:DV, IP:kmac

#24016 [Sival, Spi_host] Improve comments on the config test
  sw/device/tests/spi_host_config_test.c
  sw/host/opentitanlib/src/test_utils/bitbanging/spi.rs
  sw/host/tests/chip/spi_device/src/spi_host_config_test.rs
Labels: CherryPick:earlgrey_es_sival

#24097 [dv,jtag] Simplify tck enable/release in drive_jtag_test_logic_reset
  hw/dv/sv/jtag_agent/jtag_driver.sv
Labels: Component:DV

#24124 [chip_earlgrey_asic] Enable pull-up setting for power-on reset
  hw/top_earlgrey/rtl/autogen/chip_earlgrey_asic.sv
  util/topgen/templates/chiplevel.sv.tpl
Labels: ECO_C

#24125 [prim_count] Register err_o to avoid potential CDC issues downstream
  hw/ip/prim/rtl/prim_count.sv
Labels: ECO_C

#24127 [prim_esc_receiver] Register esc_req_o to avoid potential CDC issues
  hw/ip/prim/dv/prim_esc/tb/prim_esc_tb.sv
  hw/ip/prim/fpv/vip/prim_esc_rxtx_assert_fpv.sv
  hw/ip/prim/rtl/prim_esc_receiver.sv
Labels: ECO

#24090 [rv_dm,dv] Clear ndmreset_pending_q at start of ndmreset req vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
Labels: Component:DV, IP:rv_dm

#24096 [rv_dm,dv] Add late_debug_enable_regwen to scoreboard list of regs
  hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
Labels: Component:DV, IP:rv_dm

#24110 [otbn,dv] Avoid forcing between add/addc, sub/subb when carry=0
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv
Labels: Component:DV, IP:otbn

#23942 [kmac,dv] Check FIFO empty interrupt
  hw/ip/kmac/dv/env/kmac_scoreboard.sv
  hw/ip/kmac/dv/env/seq_lib/kmac_test_vectors_kmac_vseq.sv
Labels: Component:DV, IP:kmac

#24141 [rv_dm,dv] Set max_outstanding_req for the SBA TL agent
  hw/ip/rv_dm/dv/env/rv_dm_env_cfg.sv
Labels: Component:DV, IP:rv_dm

#24136 [rv_dm,dv] Rewrite and simplify rv_dm_dataaddr_rw_access_vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_dataaddr_rw_access_vseq.sv
Labels: Component:DV, Type:Cleanup, IP:rv_dm

#24114 [rom_ctrl,dv] Explicitly cast the return value of get_invalid_mubi4
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
Labels: Component:DV, IP:rom_ctrl

#24099 [rv_dm,dv] Extend description of some sec_cm testpoints
  hw/ip/rv_dm/data/rv_dm_sec_cm_testplan.hjson
Labels: Component:DV, IP:rv_dm

#24043 [jtag,dv] Correct FSM driving after trst_n
  hw/dv/sv/jtag_agent/jtag_driver.sv
Labels: Component:DV

#24150 [rv_dm,dv] Remove unused read_chk task
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
Labels: Component:DV, Type:Cleanup, IP:rv_dm

#24137 [rv_dm,dv] Rewrite rv_dm_hart_unavail_vseq to make it easier to read
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_hart_unavail_vseq.sv
Labels: Component:DV, Type:Cleanup, IP:rv_dm

#24093 [rv_dm,dv] Avoid repetition in rv_dm_mem_tl_access_halted_vseq
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_mem_tl_access_halted_vseq.sv
Labels: Component:DV, IP:rv_dm

#24112 [otbn,dv] Correct timing for when INSN_CNT gets zeroed in model
  hw/ip/otbn/dv/otbnsim/sim/sim.py
Labels: Component:DV, IP:otbn

#24160 [tlul] Add some missing prim dependencies in tlul_lc_gate.core
  hw/ip/tlul/tlul_lc_gate.core
Labels: IP:tlul

#24152 [rv_dm,dv] Send and abort a DMI operation
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_dmi_failed_op_vseq.sv
Labels: Component:DV, IP:rv_dm
