Repository lowRISC/opentitan, pull requests merged in 2024-11, with the labels that each got.

#24932 [hw,keymgr,dv] Fix unsupported AND within an if
  hw/ip/keymgr/dv/env/keymgr_scoreboard.sv
Labels: Component:DV

#24990 [sival] Replace nonexistent bazel targets in HMAC and KMAC testplans
  hw/top_earlgrey/data/ip/chip_hmac_testplan.hjson
  hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
Labels: CherryPick:earlgrey_1.0.0

#24965 [sdc] Add clarifying comments to SDC file
  hw/top_earlgrey/syn/chip_earlgrey_asic.sdc
Labels: ManuallyCherryPick:earlgrey_1.0.0, CherryPick:earlgrey_1.0.0

#24931 [pwm,dv] Cap number of sequences in pwm_stress_all_vseq
  hw/ip/pwm/dv/env/seq_lib/pwm_stress_all_vseq.sv
Labels: Component:DV, IP:pwm

#24958 [dvsim] Improve error handling on slurm launcher
  util/dvsim/SlurmLauncher.py
Labels: Tool:dvsim

#24156 [dv] Add GUI debug mode for Xcelium
  hw/dv/tools/common.tcl
  hw/dv/tools/dvsim/common_modes.hjson
  hw/dv/tools/dvsim/common_sim_cfg.hjson
  hw/dv/tools/dvsim/vcs.hjson
  hw/dv/tools/dvsim/xcelium.hjson
  hw/dv/tools/sim.tcl
  util/dvsim/Deploy.py
  util/dvsim/FlowCfg.py
  util/dvsim/LocalLauncher.py
  util/dvsim/SimCfg.py
  util/dvsim/dvsim.py
Labels: Tool:dvsim

#24962 [hw,dma,rtl] Update instantiation of prim_sha2_32
  hw/ip/dma/rtl/dma.sv
Labels: IP:dma

#24997 [sival] Add a few crypto/boot services test refs to testplan.
  hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
  hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
  sw/device/silicon_creator/lib/otbn_boot_services_functest.c
Labels: CherryPick:earlgrey_1.0.0

#24966 [hmac,doc] Update Save and Restore SW guide
  hw/ip/hmac/doc/programmers_guide.md
Labels: CherryPick:earlgrey_1.0.0

#25012 [hmac,sw] Poll HMAC IDLE state
  sw/device/lib/crypto/drivers/hmac.c
Labels: CherryPick:earlgrey_1.0.0

#24765 [sival,kmac] Add kmac_error_conditions_test
  hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
  sw/device/tests/BUILD
  sw/device/tests/kmac_error_conditions_test.c
Labels: CherryPick:earlgrey_1.0.0

#25070 [hmac,sw] Fix delay before context save
  sw/device/lib/crypto/drivers/hmac.c
Labels: CherryPick:earlgrey_1.0.0

#25074 [dv] Exclude some secded generation modules from coverage
  hw/dv/tools/vcs/cover.cfg
  hw/dv/tools/vcs/cover_reg_top.cfg
  hw/dv/tools/xcelium/cover.ccf
  hw/dv/tools/xcelium/cover_reg_top.ccf
Labels: Component:DV

#25060 [pwm,dv] Add a pwm_heartbeat_wrap test to see heartbeat wrapping
  hw/ip/pwm/data/pwm_testplan.hjson
  hw/ip/pwm/dv/env/pwm_env.core
  hw/ip/pwm/dv/env/seq_lib/pwm_base_vseq.sv
  hw/ip/pwm/dv/env/seq_lib/pwm_heartbeat_wrap_vseq.sv
  hw/ip/pwm/dv/env/seq_lib/pwm_vseq_list.sv
  hw/ip/pwm/dv/pwm_sim_cfg.hjson
Labels: Component:DV, IP:pwm

#24400 Exclude mem init dynamic `if` from synthesis
  hw/ip/prim/rtl/prim_util_memload.svh
Labels: CI:Rerun

#25099 [tests] Adapt one test broken by cherry-pick #23398
  sw/host/tests/chip/spi_device/src/spi_host_config_test.rs
Labels: Component:SiliconValidation

#25027 [sival,testplans] Update testplans for cpu and alert info tests
  hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
  hw/top_earlgrey/data/ip/chip_rstmgr_testplan.hjson
Labels: CherryPick:earlgrey_1.0.0

#25063 [pwm,rtl] Recode a 3-way selector to avoid a coverage hole
  hw/ip/pwm/rtl/pwm_chan.sv
Labels: Component:RTL, IP:pwm

#25110 [sival,i2c] Fix and re-enable I2C target test by adding config ujson CRC
  sw/device/tests/BUILD
  sw/device/tests/i2c_target_test.c
  sw/host/opentitanlib/src/test_utils/i2c_target.rs
Labels: CherryPick:earlgrey_1.0.0

#24523 [sw,dv] Add support for basic `status_t` (%r) logging in DV tests
  util/device_sw_utils/extract_sw_logs.py
Labels: CherryPick:earlgrey_1.0.0

#25134 [SiVal, spi_host] Update execution environment of macronix test
  sw/device/tests/pmod/BUILD
Labels: CherryPick:earlgrey_1.0.0

#25053 [pwm,rtl] Make calculation of some _d signals in pwm_chan.sv clearer
  hw/ip/pwm/rtl/pwm_chan.sv
Labels: Component:RTL, IP:pwm

#25054 [pwm,dv] Avoid running as UVM_HIGH by default
  hw/ip/pwm/dv/pwm_sim_cfg.hjson
Labels: Component:DV, IP:pwm

#25055 [pwm,dv] Set a sensible timeout for slowest clocks
  hw/ip/pwm/dv/pwm_sim_cfg.hjson
Labels: Component:DV, IP:pwm

#17666 [usbdev_mem] Packet memory T-L test
  sw/device/lib/dif/dif_usbdev.c
  sw/device/lib/dif/dif_usbdev.h
  sw/device/lib/testing/usb_testutils_diags.h
  sw/device/tests/BUILD
  sw/device/tests/usbdev_mem_test.c
Labels: CherryPick:earlgrey_1.0.0

#25157 [hw,keymgr_dpe,rtl] Remove flash seed input as not used currently
  hw/ip/keymgr_dpe/data/keymgr_dpe.hjson
  hw/ip/keymgr_dpe/dv/env/keymgr_dpe_env_cfg.sv
  hw/ip/keymgr_dpe/dv/env/keymgr_dpe_env_pkg.sv
  hw/ip/keymgr_dpe/dv/env/keymgr_dpe_if.sv
  hw/ip/keymgr_dpe/dv/env/keymgr_dpe_scoreboard.sv
  hw/ip/keymgr_dpe/dv/tb.sv
  hw/ip/keymgr_dpe/keymgr_dpe.core
  hw/ip/keymgr_dpe/rtl/keymgr_dpe.sv
Labels: Component:MultiTop, IP:keymgr_dpe

#23605 [sival] Enable high UART baud rates on silicon
  sw/device/tests/uart_baud_rate_test.c
Labels: CherryPick:master

#25113 [sival,kmac] Add chip_sw_kmac_entropy test
  hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
  sw/device/tests/BUILD
  sw/device/tests/kmac_entropy_test.c
Labels: CherryPick:earlgrey_1.0.0

#25173 [SiVal] Fix branch name when publishing the nightlies resport
  .github/workflows/nightly.yml
Labels: CherryPick:earlgrey_1.0.0

#25190 [i2c, sival] Reduce I2C bitbanging flakiness by separating SDA and SCL pin writes
  sw/host/opentitanlib/src/test_utils/bitbanging/i2c.rs
Labels: CherryPick:earlgrey_1.0.0

#24574 [sival/aes] Introduce aes_force_prng_reseed_test and aes_prng_reseed_test
  hw/top_earlgrey/data/ip/chip_aes_testplan.hjson
  sw/device/tests/BUILD
  sw/device/tests/aes_force_prng_reseed_test.c
  sw/device/tests/aes_prng_reseed_test.c
Labels: CherryPick:earlgrey_1.0.0

#25282 [sival] Add ibex testplan to top_earlgrey plan
  hw/top_earlgrey/data/chip_testplan.hjson
Labels: CherryPick:master

#25073 [pwm,dv] Exclude impossible toggle coverage in u_reg.u_chk
  hw/ip/pwm/dv/cov/cover.ccf
  hw/ip/pwm/dv/cov/toggle.exclude
  hw/ip/pwm/dv/pwm_sim_cfg.hjson
Labels: Component:DV, IP:pwm

#25280 [rom_ext] Remove AST patch functionality.
  sw/device/silicon_creator/lib/drivers/BUILD
  sw/device/silicon_creator/lib/drivers/ast.c
  sw/device/silicon_creator/rom_ext/rom_ext.c
Labels: CherryPick:master

#25266 [hmac,doc] Update for arbitrary key length
  hw/ip/hmac/README.md
  hw/ip/hmac/data/hmac.hjson
  hw/ip/hmac/doc/registers.md
  hw/ip/hmac/doc/theory_of_operation.md
Labels: CherryPick:earlgrey_1.0.0

#25001 [ci] Move Verilated Earl Grey tests to GitHub Actions
  .github/workflows/ci.yml
  azure-pipelines.yml
Labels: CherryPick:earlgrey_1.0.0

#25308 [openocd] fix openocd build on new versions of GCC
  third_party/openocd/calloc_transpose.patch
  third_party/openocd/repos.bzl
Labels: CherryPick:earlgrey_es_sival, CherryPick:master

#25299 Create usbdev_toggle_restore_test
  hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
  sw/device/tests/BUILD
  sw/device/tests/usbdev_toggle_restore_test.c
Labels: CherryPick:earlgrey_1.0.0

#25369 [ci] limit cherry-pick workflow concurrency per PR
  .github/workflows/cherrypick.yml
Labels: CherryPick:earlgrey_1.0.0

#25322 [sival] Assign `gpio_pinmux_test` to two points
  hw/top_earlgrey/data/chip_testplan.hjson
Labels: CherryPick:master

#25183 [test] Improve reliability of UART baud rate test
  sw/device/tests/uart_baud_rate_test.c
Labels: CherryPick:earlgrey_1.0.0

#25374 [sival] Enable CW310 exec env on rv_dm tests
  sw/device/tests/BUILD
Labels: CherryPick:earlgrey_1.0.0

#25326 [crypto] Consolidate P-256 binaries for OTBN.
  sw/device/lib/crypto/impl/BUILD
  sw/device/lib/crypto/impl/ecc.c
  sw/device/lib/crypto/impl/ecc/BUILD
  sw/device/lib/crypto/impl/ecc/ecdh_p256.c
  sw/device/lib/crypto/impl/ecc/ecdh_p256.h
  sw/device/lib/crypto/impl/ecc/ecdsa_p256.c
  sw/device/lib/crypto/impl/ecc/ecdsa_p256.h
  sw/device/lib/crypto/impl/ecc/p256.c
  sw/device/lib/crypto/impl/ecc/p256.h
  sw/device/lib/crypto/impl/ecc/p256_common.c
  sw/device/lib/crypto/impl/ecc/p256_common.h
  sw/device/silicon_creator/manuf/lib/personalize.h
  sw/device/tests/BUILD
  sw/device/tests/crypto/BUILD
  sw/device/tests/crypto/cryptotest/firmware/BUILD
  sw/device/tests/crypto/cryptotest/firmware/ecdh.c
  sw/device/tests/crypto/cryptotest/firmware/ecdsa.c
  sw/device/tests/crypto/ecdsa_p256_verify_functest.c
  sw/device/tests/crypto/ecdsa_p256_verify_testvectors.h.tpl
  sw/device/tests/otbn_ecdsa_op_irq_test.c
  sw/otbn/crypto/BUILD
  sw/otbn/crypto/p256_ecdsa.s
  sw/otbn/crypto/run_p256.s
  sw/otbn/crypto/tests/BUILD
Labels: CherryPick:earlgrey_1.0.0

#25116 [pwm,dv] Convert pwm_monitor to use out-of-block definitions
  hw/dv/sv/pwm_monitor/pwm_monitor.sv
Labels: Component:DV, IP:pwm

#25288 [i2c,dv] Add missing "void" type to a function in i2c_monitor
  hw/dv/sv/i2c_agent/i2c_monitor.sv
Labels: Component:DV, IP:i2c

#25393 [SiVal] Run broken tests in the sival nightlies
  .github/workflows/nightly.yml
Labels: CherryPick:earlgrey_1.0.0

#25395 [sival] Enable `pwrmgr_all_reset_reqs_test` for FPGA
  sw/device/tests/BUILD
Labels: CherryPick:earlgrey_1.0.0

#25386 [darjeeling,lint] Waive some common errors
  hw/top_darjeeling/lint/top_darjeeling.waiver
Labels: Component:Darjeeling

#25144 [tl,dv] Avoid silly hole in tl_a_chan_cov_cg
  hw/dv/sv/tl_agent/tl_agent_cov.sv
Labels: Component:DV, IP:tlul

#25434 [SiVal, usbdev] Fix usbdev tests
  sw/device/tests/BUILD
Labels: CherryPick:earlgrey_1.0.0

#25443 [dv,shadow_reg_errors] Test the last shadowed CSR
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh
Labels: CherryPick:earlgrey_1.0.0

#25391 [crypto] Consolidate P-384 OTBN binaries.
  sw/device/lib/crypto/impl/BUILD
  sw/device/lib/crypto/impl/ecc.c
  sw/device/lib/crypto/impl/ecc/BUILD
  sw/device/lib/crypto/impl/ecc/ecdh_p384.c
  sw/device/lib/crypto/impl/ecc/ecdh_p384.h
  sw/device/lib/crypto/impl/ecc/ecdsa_p384.h
  sw/device/lib/crypto/impl/ecc/ecdsa_p384_keygen.c
  sw/device/lib/crypto/impl/ecc/ecdsa_p384_keygen.h
  sw/device/lib/crypto/impl/ecc/ecdsa_p384_sign.c
  sw/device/lib/crypto/impl/ecc/ecdsa_p384_sign.h
  sw/device/lib/crypto/impl/ecc/ecdsa_p384_verify.c
  sw/device/lib/crypto/impl/ecc/ecdsa_p384_verify.h
  sw/device/lib/crypto/impl/ecc/p384.c
  sw/device/lib/crypto/impl/ecc/p384.h
  sw/device/lib/crypto/impl/ecc/p384_common.c
  sw/device/lib/crypto/impl/ecc/p384_common.h
  sw/otbn/crypto/BUILD
  sw/otbn/crypto/p384_curve_point_valid.s
  sw/otbn/crypto/p384_ecdsa_keygen.s
  sw/otbn/crypto/p384_ecdsa_sign.s
  sw/otbn/crypto/p384_ecdsa_verify.s
  sw/otbn/crypto/p384_scalar_mult.s
  sw/otbn/crypto/p384_verify.s
  sw/otbn/crypto/run_p384.s
  sw/otbn/crypto/tests/BUILD
  sw/otbn/crypto/tests/p384_ecdh_shared_key_test.s
  sw/otbn/crypto/tests/p384_ecdsa_verify_test.s
  sw/otbn/crypto/tests/p384_scalar_mult_test.s
Labels: CherryPick:earlgrey_1.0.0

#25445 [sival, keymgr] Align testplan with the new tests
  hw/top_earlgrey/data/ip/chip_keymgr_testplan.hjson
Labels: CherryPick:earlgrey_1.0.0

#25467 [pwm,dv] Don't refer to removed pwm_cov_bind
  hw/ip/pwm/dv/pwm_sim_cfg.hjson
  util/verible-format-allowlist.txt
Labels: Component:DV, IP:pwm
