Repository lowRISC/opentitan, pull requests merged in 2024-02, with the labels that each got.

#21140 [hw,prim_sha2] Fix syntax error in waiver file
  hw/ip/prim/lint/prim_sha2.waiver
Labels: Component:Darjeeling

#21070 ROM Patch Specification Changes
  hw/ip/rv_core_ibex/doc/boot-rom-patching.md
  hw/ip/rv_core_ibex/doc/patch-match.svg
Labels: Component:Darjeeling

#21135 [keymgr_dpe, dv] fix for keymgr_dpe smoke failure
  hw/ip/keymgr_dpe/dv/env/seq_lib/keymgr_dpe_base_vseq.sv
Labels: Component:Darjeeling

#21146 [hw,ibex,doc] Follow-up fixes to the ROM patching spec
  hw/ip/rv_core_ibex/doc/boot-rom-patching.md
Labels: Component:Darjeeling

#20772 [sca] Prepare KMAC for pen. tests on discrete
  sw/device/tests/crypto/cryptotest/firmware/BUILD
  sw/device/tests/crypto/cryptotest/firmware/kmac_sca.c
  sw/device/tests/crypto/cryptotest/json/kmac_sca_commands.h
Labels: Status:Ready to merge, CherryPick:earlgrey_es_sival

#20946 [sca] Fix trigger parsing
  sw/device/tests/crypto/cryptotest/firmware/trigger_sca.c
  sw/device/tests/crypto/cryptotest/json/trigger_sca_commands.h
Labels: Status:Ready to merge, CherryPick:earlgrey_es_sival

#21093 [sca] Prepare SHA3 for pen. tests
  sw/device/tests/crypto/cryptotest/firmware/BUILD
  sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
  sw/device/tests/crypto/cryptotest/json/sha3_sca_commands.h
Labels: Status:Ready to merge, CherryPick:master

#21154 [doc] Pin dashboards to last known good run
  util/site-dashboard/ot-nightly-results.js
  util/site/fetch_block_stats.py
Labels: kokoro:rebuild, kokoro:force-run

#20958 [rv_dm,dv] Add a trivial clocking block to rv_dm_if
  hw/ip/rv_dm/dv/env/rv_dm_if.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_cmderr_halt_resume_vseq.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_hart_unavail_vseq.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_jtag_dmi_debug_disabled_vseq.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_smoke_vseq.sv
Labels: Component:DV, Type:Cleanup

#21147 [ot_certs,codegen] Avoid the use of strlen for string literals.
  sw/host/ot_certs/src/asn1/codegen.rs
Labels: CherryPick:earlgrey_es_sival

#20901 [prim] Avoid unnecessary Impl parameter in prim_onehot_check
  hw/ip/prim/rtl/prim_onehot_check.sv
Labels: Component:DV, Component:RTL, IP:prim

#21046 [cryptolib] KDF API changes
  doc/security/cryptolib/cryptolib_api.md
  sw/device/lib/crypto/impl/kdf.c
  sw/device/lib/crypto/include/datatypes.h
  sw/device/lib/crypto/include/kdf.h
Labels: Status:Ready to merge

#20919 [rv_dm,dv] Remove TODOs when setting reset values in env cfgs
  hw/ip/rv_dm/dv/env/rv_dm_env_cfg.sv
  hw/top_earlgrey/dv/env/chip_env_cfg.sv
Labels: Component:DV, IP:rv_dm

#20667 [primgen] Fix parameters in a primgen template
  hw/ip/prim/util/primgen/abstract_prim.sv.tpl
Labels: Component:Tooling, IP:prim

#21186 [prim_clock_div,lint] Update waiver to cover renamed signals
  hw/ip/prim/lint/prim_clock_div.waiver
Labels: Component:Darjeeling

#20895 [hw,mbx,rtl] Clear interrupts when acknowledging an abort
  hw/ip/mbx/rtl/mbx.sv
  hw/ip/mbx/rtl/mbx_hostif.sv
  hw/ip/mbx/rtl/mbx_sysif.sv
Labels: Component:RTL, Component:Darjeeling

#21161 [spi_device] Remove all timing mode CSRs
  hw/ip/spi_device/data/spi_device.hjson
  hw/ip/spi_device/doc/registers.md
  hw/ip/spi_device/doc/theory_of_operation.md
  hw/ip/spi_device/dv/env/seq_lib/spi_device_pass_base_vseq.sv
  hw/ip/spi_device/dv/env/seq_lib/spi_device_tpm_base_vseq.sv
  hw/ip/spi_device/rtl/spi_device.sv
  hw/ip/spi_device/rtl/spi_device_reg_pkg.sv
  hw/ip/spi_device/rtl/spi_device_reg_top.sv
  hw/ip/spi_device/rtl/spi_p2s.sv
  hw/ip/spi_device/rtl/spi_passthrough.sv
  sw/device/lib/dif/dif_spi_device.c
  sw/device/lib/dif/dif_spi_device.h
  sw/device/lib/dif/dif_spi_device_unittest.cc
  sw/device/lib/testing/spi_device_testutils.c
  sw/device/lib/testing/test_framework/ottf_console.c
  sw/device/silicon_creator/lib/drivers/spi_device.c
  sw/device/silicon_creator/lib/drivers/spi_device_unittest.cc
  sw/device/tests/rstmgr_sw_rst_ctrl_test.c
Labels: Component:RTL, IP:spi_device

#21121 [pentest] Add SCA/FI pen. test bazel rule
  sw/device/tests/crypto/cryptotest/firmware/BUILD
Labels: Status:Ready to merge, CherryPick:master

#21137 [rom_ext,rescue] Rescue protocol infrastructure
  sw/device/silicon_creator/lib/drivers/BUILD
  sw/device/silicon_creator/lib/drivers/ibex.c
  sw/device/silicon_creator/lib/drivers/ibex.h
  sw/device/silicon_creator/lib/drivers/ibex_host.c
  sw/device/silicon_creator/lib/drivers/pinmux.c
  sw/device/silicon_creator/lib/drivers/pinmux.h
  sw/device/silicon_creator/lib/drivers/uart.c
  sw/device/silicon_creator/lib/drivers/uart.h
  sw/device/silicon_creator/lib/drivers/uart_unittest.cc
Labels: CherryPick:master

#21221 [sival, spi_host] Add test chip_sw_spi_host_events to sival
  hw/top_earlgrey/data/ip/chip_spi_host_testplan.hjson
  sw/device/tests/BUILD
  sw/device/tests/sival/BUILD
  sw/device/tests/spi_host_irq_test.c
Labels: CherryPick:master

#21198 [bazel] Create a static library link rule
  rules/opentitan/static_library.bzl
  sw/device/lib/crypto/BUILD
Labels: CherryPick:earlgrey_es_sival

#21165 [ot_certs] Make sure that EC public key creates padded integers
  sw/device/silicon_creator/lib/cert/asn1.c
  sw/device/silicon_creator/lib/cert/asn1.h
  sw/device/silicon_creator/lib/cert/asn1_unittest.cc
  sw/host/ot_certs/src/asn1/codegen.rs
  sw/host/ot_certs/src/template/subst.rs
Labels: CherryPick:earlgrey_es_sival

#21190 [dv] Tweaks to csr_peek to make the code simpler
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq__shadow_reg_errors.svh
  hw/dv/sv/csr_utils/csr_utils_pkg.sv
  hw/ip/entropy_src/dv/env/entropy_src_scoreboard.sv
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_flash_init_vseq.sv
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_keymgr_key_derivation_vseq.sv
  hw/top_earlgrey/dv/env/seq_lib/chip_tap_straps_vseq.sv
Labels: Component:DV

#21144 [integrated_dev] Restrict RTL changes for Darjeeling and its HW IP blocks
  BLOCKFILE
Labels: Component:CI, Component:Darjeeling

#21233 [opentitanlib] Add an Xmodem-CRC implementation
  apt-requirements.txt
  sw/host/opentitanlib/BUILD
  sw/host/opentitanlib/src/bootstrap/mod.rs
  sw/host/opentitanlib/src/bootstrap/xmodem.rs
  sw/host/opentitanlib/src/util/mod.rs
  sw/host/opentitanlib/src/util/testing.rs
  sw/host/opentitantool/BUILD
  sw/host/opentitantool/src/command/mod.rs
  sw/host/opentitantool/src/command/xmodem.rs
  sw/host/opentitantool/src/main.rs
Labels: CherryPick:master

#21239 [pentest] Add prodc target to pentest build script
  sw/device/tests/crypto/cryptotest/firmware/BUILD
Labels: Status:Ready to merge, CherryPick:master

#21072 [opentitantool] HyperDebug support for baud rate and break condition
  sw/host/opentitanlib/BUILD
  sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
  sw/host/opentitanlib/src/transport/hyperdebug/uart.rs
  third_party/hyperdebug/repos.bzl
Labels: SW:opentitantool, CherryPick:master

#21264 [opentitantool] Fix for SPI chip select and opentitansession
  sw/host/opentitanlib/src/app/mod.rs
Labels: SW:opentitantool, CherryPick:earlgrey_es_sival

#21303 [sival/edn] Add EDN tests to bazel testpoint rule
  hw/top_earlgrey/data/ip/chip_edn_testplan.hjson
Labels: CherryPick:earlgrey_es_sival

#21150 [entropy_src,testplan] Add testpoints for firmware override mode
  hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
Labels: CherryPick:earlgrey_es_sival

#21336 [rom_ctrl,dv] Use DV_CHECK around some calls to uvm_hdl_read
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
Labels: Component:DV, IP:rom_ctrl

#21337 [primgen] Uniquify prim_abstract core file
  hw/ip/prim/util/primgen.py
Labels: IP:prim, Component:Darjeeling

#21323 [primgen] Use a fully specified VLNV string for prim_abstracts
  hw/ip/prim/util/primgen.py
Labels: IP:prim, Component:Darjeeling

#21333 [mbx/dv] Map missing items in test plan
  hw/ip/mbx/data/mbx_testplan.hjson
Labels: Component:DV, Component:Darjeeling, IP:mailbox

#21335 [rom_ctrl,dv] Tweak randomisation of bad mubi4_t values
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
Labels: Component:DV, IP:rom_ctrl

#21342 [rom_ctrl,dv] Start CSR accesses later in passthru_mem_tl_intg_err
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_common_vseq.sv
Labels: Component:DV, IP:rom_ctrl

#21339 [rom_ctrl,dv] Check returns of uvm_hdl_force/uvm_hdl_release
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
Labels: Component:DV, IP:rom_ctrl

#21224 [pentest] Fix KMAC SCA code
  sw/device/tests/crypto/cryptotest/firmware/kmac_sca.c
  sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
  sw/device/tests/crypto/cryptotest/json/kmac_sca_commands.h
  sw/device/tests/crypto/cryptotest/json/sha3_sca_commands.h
Labels: Status:Ready to merge, CherryPick:master

#21349 [opentitantool] Better SPI error messages from HyperDebug
  sw/host/opentitanlib/src/transport/hyperdebug/spi.rs
Labels: SW:opentitantool, CherryPick:earlgrey_es_sival

#21373 [opentitantool] Fix crippled I2C TPM support
  sw/host/opentitanlib/src/tpm/driver.rs
  sw/host/opentitantool/src/command/i2c.rs
Labels: SW:opentitantool, CherryPick:earlgrey_es_sival

#21514 [pentest] Move SHA3 trigger arm&disarm
  sw/device/sca/sha3_serial.c
  sw/device/tests/crypto/cryptotest/firmware/sha3_sca.c
Labels: CherryPick:master

#21366 [sival, spi_dev_flash] Add smoke test and link to test plan
  hw/top_earlgrey/data/ip/chip_spi_device_testplan.hjson
  sw/device/tests/BUILD
  sw/device/tests/spi_device_flash_smoketest.c
  sw/host/tests/chip/spi_device_flash_smoketest/BUILD
  sw/host/tests/chip/spi_device_flash_smoketest/src/main.rs
Labels: CherryPick:master

#21529 [chip-level/entropy_src] Link bazel tests in testplan
  hw/top_earlgrey/data/ip/chip_entropy_src_testplan.hjson
Labels: CherryPick:earlgrey_es_sival

#21525 [mbx/dif] DIF function to access IPI configuration
  sw/ip/mbx/dif/dif_mbx.c
  sw/ip/mbx/dif/dif_mbx.h
  sw/ip/mbx/dif/dif_mbx_unittest.cc
Labels: SW:DIF, Component:Darjeeling, IP:mailbox

#21340 [rom_ctrl,dv] Minor tidy-up in rom_ctrl vseqs
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_kmac_err_chk_vseq.sv
Labels: Component:DV, IP:rom_ctrl

#21623 [ci] disable CI on backport-* branches
  azure-pipelines.yml
  ci/azp-private.yml
Labels: CherryPick:earlgrey_es_sival

#21608 [bazel,silicon] Use `teacup` interface for silicon exec_env
  hw/top_earlgrey/BUILD
  sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
  sw/host/opentitanlib/src/backend/mod.rs
Labels: CherryPick:master

#21595 [spi_device] Add separate constraints for TPM and fast passthrough
  hw/top_earlgrey/syn/chip_earlgrey_asic.sdc
Labels: TOP:earlgrey

#21647 [rom_ctrl,dv] Fix constraint for invalid mubis in vseq
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_corrupt_sig_fatal_chk_vseq.sv
Labels: Component:DV, IP:rom_ctrl

#21575 [crypto] Fix a broken trap condition in RSA
  sw/device/lib/crypto/impl/rsa.c
Labels: CherryPick:earlgrey_es_sival

#21576 [crypto/rsa] temporarily use constant-time modexp when e != 0x10001
  sw/device/lib/crypto/impl/rsa/rsa_modexp.c
Labels: CherryPick:earlgrey_es_sival

#21661 [fpga_cw310_sival_rom_ext] Fix key mismatch
  hw/top_earlgrey/BUILD
  sw/device/silicon_creator/rom_ext/BUILD
Labels: Component:Tooling

#21703 [hmac] Bump version to 2.0.0 and reset development stages
  hw/ip/hmac/data/hmac.hjson
Labels: IP:hmac

#21670 [hmac,verilator] Remove lint waivers for nonexistent file
  hw/ip/hmac/lint/hmac.vlt
Labels: Component:Tooling, Type:Cleanup

#21659 [dv] Make mem_model's compare_byte function less chatty
  hw/dv/sv/mem_model/mem_model.sv
Labels: Component:DV, Type:Cleanup

#21341 [csr_seq_lib] Avoid slicing a queue
  hw/dv/sv/csr_utils/csr_seq_lib.sv
Labels: Component:DV, Type:Cleanup

#21667 [hw,spi_host,i2c,soc_proxy] Fix CDC issue for lsio_triggers
  hw/ip/spi_host/rtl/spi_host.sv
  hw/ip/uart/rtl/uart_core.sv
  hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
  hw/top_darjeeling/ip/soc_proxy/data/soc_proxy.hjson
  hw/top_darjeeling/ip/soc_proxy/rtl/soc_proxy.sv
Labels: Component:CDC, Component:Darjeeling, IP:dma

#21693 [otp] Increase OWNER_SW_CFG_ROM_ALERT_CLASSIFICATION by 4
  hw/ip/otp_ctrl/data/otp_ctrl.hjson
  hw/ip/otp_ctrl/data/otp_ctrl_img_owner_sw_cfg.hjson
  hw/ip/otp_ctrl/data/otp_ctrl_mmap.hjson
  hw/ip/otp_ctrl/doc/otp_ctrl_mmap.md
  hw/ip/otp_ctrl/rtl/otp_ctrl_part_pkg.sv
  hw/ip/otp_ctrl/rtl/otp_ctrl_reg_pkg.sv
Labels: Component:Darjeeling

#21747 [spi_device] Add missing not-X assertions for output ports
  hw/ip/spi_device/rtl/spi_device.sv
Labels: Type:Cleanup, Component:RTL, IP:spi_device

#21740 [otp] Fix OWNER_SW_CFG_ROM_ALERT_DIGEST_PROD_END value
  hw/ip/otp_ctrl/data/otp_ctrl_img_owner_sw_cfg.hjson
Labels: IP:otp_ctrl, Component:Darjeeling

#21719 [vendor/pulp_riscv_dbg] Update to pulp-platform/riscv-dbg@358f901
  hw/vendor/pulp_riscv_dbg.lock.hjson
  hw/vendor/pulp_riscv_dbg/CHANGELOG.md
  hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom.sv
  hw/vendor/pulp_riscv_dbg/debug_rom/debug_rom_one_scratch.sv
  hw/vendor/pulp_riscv_dbg/debug_rom/gen_rom.py
  hw/vendor/pulp_riscv_dbg/src/dm_mem.sv
  hw/vendor/pulp_riscv_dbg/src/dmi_jtag.sv
Labels: Component:RTL, IP:rv_dm

#21728 [cryptotest] refactor `parse_rsp` and clean up test vector build script
  sw/host/cryptotest/testvectors/data/BUILD
  sw/host/cryptotest/testvectors/parsers/BUILD
  sw/host/cryptotest/testvectors/parsers/cryptotest_util.py
  sw/host/cryptotest/testvectors/parsers/cryptotest_util_test.py
  sw/host/cryptotest/testvectors/parsers/nist_aes_parser.py
  sw/host/cryptotest/testvectors/parsers/nist_cavp_ecdsa_parser.py
  sw/host/cryptotest/testvectors/parsers/nist_cavp_hash_parser.py
  sw/host/cryptotest/testvectors/parsers/nist_cavp_hmac_parser.py
Labels: CherryPick:earlgrey_es_sival
