Repository lowRISC/opentitan, pull requests merged in 2024-12, with the labels that each got.

#25272 [alert,dv] Fix logic in alert_receiver_driver
  hw/dv/sv/alert_esc_agent/alert_receiver_driver.sv
Labels: Component:DV, IP:alert_handler

#25473 [darjeeling] Regenerate Darjeeling after tooling changes
  hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
  hw/top_darjeeling/templates/chiplevel.sv.tpl
Labels: Component:Darjeeling

#25430 [alert,dv] Tidyups in the alert receiver driver
  hw/dv/sv/alert_esc_agent/alert_receiver_driver.sv
Labels: Component:DV, IP:alert_handler

#25462 [SiVal, usbdev] Add harness to usbdev_test
  sw/device/tests/BUILD
  sw/host/tests/chip/usb/BUILD
  sw/host/tests/chip/usb/usbdev_smoketest.rs
Labels: CherryPick:earlgrey_1.0.0

#25479 [kmac, sival] Add sival exec environment to kmac_app_rom_test
  sw/device/tests/BUILD
Labels: CherryPick:earlgrey_1.0.0

#25510 [cryptotest] Add P-384 targets to cryptotest.
  sw/device/tests/crypto/cryptotest/BUILD
  sw/device/tests/crypto/cryptotest/firmware/ecdh.c
  sw/device/tests/crypto/cryptotest/firmware/ecdsa.c
Labels: CherryPick:earlgrey_1.0.0

#25290 [chip,dv] Make a cast explicit in chip_sw_rom_e2e_jtag_inject_vseq
  hw/top_earlgrey/dv/env/seq_lib/chip_sw_rom_e2e_jtag_inject_vseq.sv
Labels: Component:DV, Component:ChipLevelTest

#25481 [prim,rtl] Rephrase a term in prim_reg_cdc.sv
  hw/ip/prim/rtl/prim_reg_cdc.sv
Labels: Component:RTL, IP:prim

#25146 [rv_core_ibex, top_earlgrey] Enable SecureIbex for CW340
  hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw310.sv
  hw/top_earlgrey/rtl/autogen/chip_earlgrey_cw340.sv
  hw/top_earlgrey/templates/chiplevel.sv.tpl
Labels: CherryPick:earlgrey_1.0.0

#25537 [sival] Enable CW340 exec. environment for ECC tests
  sw/device/tests/BUILD
  sw/device/tests/sram_ctrl_scrambled_access_test.c
Labels: CherryPick:earlgrey_1.0.0

#25543 [sival, spi] Add missing argument for passthru test harness on silicon
  sw/device/tests/BUILD
Labels: CherryPick:earlgrey_1.0.0

#25531 [opentitantool] Include updated firmware for HyperDebug
  third_party/hyperdebug/repos.bzl
Labels: SW:opentitantool, CherryPick:earlgrey_es_sival, CherryPick:earlgrey_1.0.0

#24511 [prim,lint] Remove waiver for prim_sram_arbiter.sv
  hw/ip/prim/lint/prim.waiver
Labels: IP:prim

#24510 [prim,lint] Remove waiver for prim_subreg.sv
  hw/ip/prim/lint/prim_subreg.waiver
Labels: IP:prim

#24495 [prim,rtl] Remove dead code in prim_fifo_async_sram_adapter
  hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv
Labels: Component:FPV, IP:prim

#25570 [SiVal, usbdev] Link tx_rx_test to vbus_test in tesplan
  hw/top_earlgrey/data/ip/chip_usbdev_testplan.hjson
Labels: CherryPick:earlgrey_1.0.0

#25587 [rom_ctrl,dv] Fix how we splat fifo contents in common vseq
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_common_vseq.sv
Labels: Component:DV, IP:rom_ctrl

#25557 [hmac,doc] S&R reg changes when IDLE
  hw/ip/hmac/data/hmac.hjson
  hw/ip/hmac/doc/registers.md
Labels: CherryPick:earlgrey_1.0.0

#25597 [sw,rnd] Fix polling loop for RND_DATA_VALID
  sw/device/silicon_creator/lib/drivers/rnd.c
Labels: CherryPick:earlgrey_1.0.0

#25643 [ci] Move CW305 bitstream build to machine without license
  .github/workflows/ci.yml
Labels: CherryPick:earlgrey_1.0.0

#25612 [dv] Avoid timing out if we call tl_access_sub lots in parallel
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
  hw/dv/sv/tl_agent/seq_lib/tl_host_seq.sv
Labels: Component:DV

#25611 [dv] Be more careful not to leave orphan processes in clk_rst_if
  hw/dv/sv/common_ifs/clk_rst_if.sv
Labels: Component:DV

#25586 [rom_ctrl,dv] Correct argument to dut_init in rom_ctrl_base_vseq
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
Labels: Component:DV, IP:rom_ctrl

#25061 [pwm,dv] Lower some reseed counts
  hw/ip/pwm/dv/pwm_sim_cfg.hjson
Labels: Component:DV, IP:pwm

#25629 [opentitantool] HyperDebug firmware fix
  third_party/hyperdebug/repos.bzl
Labels: SW:opentitantool

#25532 [sival/entropy_src] Add entropy_src_bypass_mode_health_test
  sw/device/tests/BUILD
  sw/device/tests/entropy_src_bypass_mode_health_test.c
Labels: CherryPick:earlgrey_1.0.0

#25655 [alert, sival] chip_sw_alert_handler_escalation
  hw/top_earlgrey/data/ip/chip_alert_handler_testplan.hjson
  hw/top_earlgrey/dv/chip_sim_cfg.hjson
  sw/device/tests/BUILD
  sw/device/tests/alert_handler_escalation_test.c
  sw/device/tests/sim_dv/BUILD
Labels: CherryPick:earlgrey_1.0.0

#25662 [SiVal] Add the cw340 exec_env to crypto tests
  sw/device/tests/crypto/BUILD
Labels: CherryPick:earlgrey_1.0.0

#25652 [opentitanlib] set EXEC CSR in sram_ctrl when SRAM program is loaded
  sw/device/silicon_creator/manuf/tests/BUILD
  sw/host/opentitanlib/bindgen/BUILD
  sw/host/opentitanlib/bindgen/difs.h
  sw/host/opentitanlib/src/test_utils/load_sram_program.rs
Labels: CherryPick:master

#25431 [alert,dv] Use priorities in alert agent arbitration
  hw/dv/sv/alert_esc_agent/alert_esc_agent.sv
Labels: Component:DV, IP:alert_handler

#23374 [jtag,dv] Demote some driver messages to UVM_HIGH
  hw/dv/sv/jtag_agent/jtag_driver.sv
Labels: Component:DV

#25699 [reggen] Describe REGWEN properly for multi-registers
  hw/ip/dma/doc/registers.md
  hw/ip/keymgr/doc/registers.md
  hw/ip/kmac/doc/registers.md
  hw/ip/lc_ctrl/doc/registers.md
  hw/ip/otp_ctrl/doc/registers.md
  hw/ip/pwm/doc/registers.md
  hw/ip/rv_core_ibex/doc/registers.md
  hw/ip/sysrst_ctrl/doc/registers.md
  hw/top_darjeeling/ip_autogen/pinmux/doc/registers.md
  hw/top_darjeeling/ip_autogen/rstmgr/doc/registers.md
  hw/top_earlgrey/ip/sensor_ctrl/doc/registers.md
  hw/top_earlgrey/ip_autogen/flash_ctrl/doc/registers.md
  hw/top_earlgrey/ip_autogen/pinmux/doc/registers.md
  hw/top_earlgrey/ip_autogen/rstmgr/doc/registers.md
  util/reggen/gen_md.py
Labels: Component:Doc, Tool:reggen

#25698 [SiVal] Map manufacture tests to the testplans
  sw/device/silicon_creator/manuf/data/manuf_testplan.hjson
  sw/device/silicon_creator/manuf/tests/BUILD
Labels: CherryPick:earlgrey_1.0.0

#25694 [crypto] Harden RSA modexp subroutine.
  sw/otbn/crypto/modexp.s
Labels: CherryPick:earlgrey_1.0.0

#25723 [SiVal] Fix bazel target in testsplans
  hw/top_earlgrey/data/ip/chip_lc_ctrl_testplan.hjson
  sw/device/silicon_creator/manuf/data/manuf_testplan.hjson
Labels: CherryPick:earlgrey_1.0.0

#25199 [hw,spi_host,rtl] Increase command length register to 20 bit
  hw/ip/spi_host/data/spi_host.hjson
  hw/ip/spi_host/doc/registers.md
  hw/ip/spi_host/dv/README.md
  hw/ip/spi_host/dv/env/spi_host_env_pkg.sv
  hw/ip/spi_host/rtl/spi_host_cmd_pkg.sv
  hw/ip/spi_host/rtl/spi_host_fsm.sv
  hw/ip/spi_host/rtl/spi_host_reg_pkg.sv
  hw/ip/spi_host/rtl/spi_host_reg_top.sv
Labels: IP:spi_host

#25741 [SiVal, manuf] Fix bazel target in testplan
  sw/device/silicon_creator/manuf/data/manuf_testplan.hjson
Labels: CherryPick:earlgrey_1.0.0
