Repository lowRISC/opentitan, pull requests merged in 2024-08, with the labels that each got.

#24116 Pull shared objects out of Hyperdebug Transport Inner member
  sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
Labels: SW:opentitantool, CherryPick:earlgrey_es_sival

#23687 [hw,dma,rtl] Only set error code when entering the error state
  hw/ip/dma/rtl/dma.sv
Labels: Component:Darjeeling, IP:dma

#24200 [opentitantool] Avoid repeated opening/closing
  sw/host/opentitanlib/opentitantool_derive/src/lib.rs
  sw/host/opentitanlib/src/app/command.rs
  sw/host/opentitanlib/src/app/mod.rs
  sw/host/opentitanlib/src/transport/hyperdebug/mod.rs
  sw/host/opentitanlib/src/transport/mod.rs
  sw/host/opentitansession/src/main.rs
  sw/host/opentitantool/src/command/console.rs
  sw/host/opentitantool/src/main.rs
Labels: SW:opentitantool, CherryPick:earlgrey_es_sival

#24140 [rv_dm,dv] Expand the rv_dm_progbuf_read_write_execute test
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_progbuf_read_write_execute_vseq.sv
Labels: Component:DV, IP:rv_dm

#23369 [util] Get rid of "type" field in Modes
  util/dvsim/Regression.py
  util/dvsim/modes.py
Labels: Component:DV, Tool:dvsim

#24227 [sensor_ctrl] Renew D3 signoff
  hw/top_earlgrey/ip/sensor_ctrl/doc/checklist.md
Labels: IP:sensor_ctrl

#24243 [rv_dm,dv] Remove bogus TODO note from me
  hw/ip/rv_dm/dv/env/rv_dm_scoreboard.sv
Labels: Component:DV, IP:rv_dm

#23274 [topgen] Generically filter for MMIO region visible devices
  hw/top_darjeeling/data/autogen/top_darjeeling.gen.hjson
  hw/top_darjeeling/data/top_darjeeling.hjson
  hw/top_darjeeling/sw/autogen/chip/top_darjeeling.rs
  hw/top_darjeeling/sw/autogen/chip/top_darjeeling_memory.rs
  hw/top_darjeeling/sw/autogen/top_darjeeling.h
  hw/top_darjeeling/sw/autogen/top_darjeeling_memory.h
  hw/top_earlgrey/data/autogen/top_earlgrey.gen.hjson
  hw/top_earlgrey/data/top_earlgrey.hjson
  util/topgen/c.py
  util/topgen/lib.py
  util/topgen/rust.py
  util/topgen/templates/toplevel.h.tpl
  util/topgen/templates/toplevel.rs.tpl
  util/topgen/templates/toplevel_memory.h.tpl
  util/topgen/templates/toplevel_memory.rs.tpl
  util/topgen/validate.py
Labels: Component:Tooling, Component:Darjeeling

#24171 [otbn,dv] Don't expect specific pre-decode checks in ctrl_redun_vseq
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv
Labels: Component:DV, IP:otbn

#24249 [usbdev,dv] UNR exclusions
  hw/ip/usbdev/dv/cov/usbdev_unr_excl.el
  hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Labels: ManuallyCherryPick:earlgrey_1.0.0

#24253 Revert "[dv] Add a quick exit in csr_rd_sub when in reset"
  hw/dv/sv/csr_utils/csr_utils_pkg.sv
Labels: Component:DV, ManuallyCherryPick:earlgrey_1.0.0

#24204 [csrng/dv] Properly trigger the status error responses
  hw/dv/sv/csrng_agent/csrng_agent_cov.sv
  hw/ip/csrng/dv/cov/csrng_cov_if.sv
  hw/ip/csrng/dv/env/csrng_env_cfg.sv
  hw/ip/csrng/dv/env/seq_lib/csrng_intr_vseq.sv
  hw/ip/edn/dv/cov/edn_cov_if.sv
Labels: ManuallyCherryPick:earlgrey_1.0.0

#24237 [edn/dv] Allow flopped error output of prim_count to propagate to CSRs
  hw/ip/edn/dv/env/seq_lib/edn_common_vseq.sv
Labels: ManuallyCherryPick:earlgrey_1.0.0

#24209 [top_earlgrey,cdc] Transition to MeridianCDC
  hw/cdc/tools/dvsim/common_cdc_cfg.hjson
  hw/cdc/tools/dvsim/meridiancdc.hjson
  hw/cdc/tools/dvsim/verixcdc.hjson
  hw/cdc/tools/meridiancdc/run-cdc.tcl
  hw/cdc/tools/verixcdc/run-cdc.tcl
  hw/top_earlgrey/cdc/chip_earlgrey_asic_cdc_cfg.hjson
  hw/top_earlgrey/cdc/user_intent.env
  util/dvsim/verixcdc-report-parser.py
Labels: TOP:earlgrey, Component:CDC, ManuallyCherryPick:earlgrey_1.0.0

#24218 [otp_ctrl] Sign v2.0.0 off at D3
  hw/ip/otp_ctrl/data/otp_ctrl.hjson
  hw/ip/otp_ctrl/data/otp_ctrl.hjson.tpl
  hw/ip/otp_ctrl/doc/checklist.md
Labels: IP:otp_ctrl

#24163 [rtl,clkmgr] Declare clkmgr at D3
  hw/ip_templates/clkmgr/data/clkmgr.hjson.tpl
  hw/ip_templates/clkmgr/doc/checklist.md
  hw/top_earlgrey/ip_autogen/clkmgr/data/clkmgr.hjson
  hw/top_earlgrey/ip_autogen/clkmgr/doc/checklist.md
Labels: ManuallyCherryPick:earlgrey_1.0.0

#24229 [lc_ctrl] Move LC_CTRL version 2.0.0 design_stage to D3
  hw/ip/lc_ctrl/data/lc_ctrl.hjson
  hw/ip/lc_ctrl/doc/checklist.md
Labels: ManuallyCherryPick:earlgrey_1.0.0

#24257 [dv,usbdev] Add coverage exclusions for dynamic USB behavior
  hw/ip/usbdev/dv/cov/usbdev_manual_excl.el
  hw/ip/usbdev/dv/usbdev_sim_cfg.hjson
Labels: ManuallyCherryPick:earlgrey_1.0.0

#24250 [otbn,dv] Correct timing after injecting one type of error
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_ctrl_redun_vseq.sv
Labels: Component:DV, IP:otbn, ManuallyCherryPick:earlgrey_1.0.0

#24261 [dv,jtag] Improvements in jtag driver
  hw/dv/sv/jtag_agent/jtag_driver.sv
Labels: Component:DV

#24244 [edn/dv] Edn cover csrng sts errs
  hw/ip/edn/dv/cov/edn_cov_if.sv
  hw/ip/edn/dv/env/seq_lib/edn_alert_vseq.sv
Labels: ManuallyCherryPick:earlgrey_1.0.0

#24036 [dv] Chop reset delay by a factor of 100 in cip_base_vseq
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
Labels: Component:DV

#24094 [rv_dm,dv] Remove the "good prefix" of sba_debug_disabled testpoint
  hw/ip/rv_dm/data/rv_dm_testplan.hjson
Labels: Component:DV, IP:rv_dm

#24264 [dv] Exit quickly from check_no_fatal_alerts on reset
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
Labels: Component:DV

#24263 [dv,jtag] Teach jtag_dmi_reg_frontdoor to handle resets
  hw/dv/sv/jtag_dmi_agent/jtag_dmi_reg_frontdoor.sv
Labels: Component:DV

#24266 [dv] Define a more robust "resetting procedure" for vseqs
  hw/dv/sv/cip_lib/cip_base_env_cfg.sv
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
Labels: Component:DV

#24113 [otbn,dv] Factor out tasks in otbn_sec_wipe_err_vseq.sv
  hw/ip/otbn/dv/uvm/env/seq_lib/otbn_sec_wipe_err_vseq.sv
Labels: Component:DV, IP:otbn

#24288 [dv] Manually apply specialisation for mubi32_cov
  hw/dv/sv/dv_base_reg/dv_base_mubi_cov.sv
Labels: Component:DV

#24300 [dv,doc] Fix layout in cip_lib/README.md
  hw/dv/sv/cip_lib/README.md
Labels: Component:Doc, Component:DV

#24280 [rv_dm,dv] Add sparse FSM tests
  hw/ip/rv_dm/data/rv_dm_sec_cm_testplan.hjson
  hw/ip/rv_dm/dv/env/rv_dm_env.core
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_sparse_lc_gate_fsm_vseq.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
  hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
Labels: Component:DV, IP:rv_dm

#24275 [tl,dv] Remove d_error check from bus2reg in reg adapter
  hw/dv/sv/tl_agent/tl_reg_adapter.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_debug_disabled_vseq.sv
Labels: Component:DV

#24282 [rv_dm,dv] Drop a wait from dut_shutdown
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
Labels: Component:DV, IP:rv_dm

#24286 [dv,pwrmgr] Remove remaining TODOs
  hw/ip_templates/pwrmgr/data/pwrmgr_testplan.hjson
  hw/ip_templates/pwrmgr/doc/checklist.md
  hw/ip_templates/pwrmgr/dv/env/seq_lib/pwrmgr_escalation_timeout_vseq.sv
  hw/top_earlgrey/ip_autogen/pwrmgr/data/pwrmgr_testplan.hjson
  hw/top_earlgrey/ip_autogen/pwrmgr/doc/checklist.md
  hw/top_earlgrey/ip_autogen/pwrmgr/dv/env/seq_lib/pwrmgr_escalation_timeout_vseq.sv
Labels: CherryPick:earlgrey_es_sival

#24302 [rv_dm,dv] Start using can_reset_with_csr_accesses in rv_dm
  hw/ip/rv_dm/dv/env/rv_dm_env_cfg.sv
Labels: Component:DV, IP:rv_dm

#24307 [rv_dm,dv] Add a scanmode sequence
  hw/ip/rv_dm/dv/env/rv_dm_env.core
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_base_vseq.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_scanmode_vseq.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_vseq_list.sv
  hw/ip/rv_dm/dv/rv_dm_sim_cfg.hjson
Labels: Component:DV, IP:rv_dm

#24329 [rom_ctrl,dv] Remove irrelevant coverpoint from rom_ctrl_tlul_cg
  hw/ip/rom_ctrl/dv/cov/rom_ctrl_cov_if.sv
Labels: Component:DV, IP:rom_ctrl

#24327 [rom_ctrl,dv] Make some assertions terminate, improving coverage
  hw/ip/rom_ctrl/rtl/rom_ctrl.sv
Labels: Component:DV, IP:rom_ctrl

#24324 [rom_ctrl,dv] Allow words in the expected digest to not all be wrong
  hw/ip/rom_ctrl/dv/env/seq_lib/rom_ctrl_base_vseq.sv
Labels: Component:DV, IP:rom_ctrl

#24276 [rv_dm,dv] Exclude StFlush state coverage in a tlul_lc_gate instance
  hw/ip/rv_dm/dv/cov/rv_dm_cov_excl.el
Labels: Component:DV, IP:rv_dm

#24335 [rv_dm,dv,doc] Expand the DV document to describe the current state
  hw/ip/rv_dm/dv/README.md
Labels: Component:Doc, Component:DV, IP:rv_dm

#24336 [rv_dm,dv] Hit minor conditional coverage hole for ndmreset signals
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
Labels: Component:DV, IP:rv_dm

#24301 [dv,doc] Document can_reset_with_csr_accesses in cip_lib/README.md
  hw/dv/sv/cip_lib/README.md
Labels: Component:Doc, Component:DV

#24328 [dv] Allow assertions from ASSERT_FPV_LINEAR_FSM to complete
  hw/ip/prim/rtl/prim_assert.sv
Labels: Component:DV

#24347 [otbn,dv] Weaken an assertion about tracking busy/locking state
  hw/ip/otbn/rtl/otbn.sv
Labels: Component:DV, IP:otbn

#24373 [sram_ctrl,dv] Wait with reset after mem_init
  hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_stress_all_vseq.sv
Labels: ManuallyCherryPick:earlgrey_1.0.0

#24403 Update lowrisc_ibex to lowRISC/ibex@38c07093
  hw/vendor/lowrisc_ibex.lock.hjson
  hw/vendor/lowrisc_ibex/rtl/ibex_controller.sv
Labels: ECO, ManuallyCherryPick:earlgrey_1.0.0

#24383 [earlgrey_1.0.0] Ibex timing fix
  hw/vendor/lowrisc_ibex.lock.hjson
  hw/vendor/lowrisc_ibex/rtl/ibex_controller.sv
Labels: ECO

#24326 [rom_ctrl,dv] Avoid an injected FSM error causing a test failure
  hw/ip/rom_ctrl/dv/env/rom_ctrl_scoreboard.sv
Labels: Component:DV, IP:rom_ctrl

#24432 [prim,fpv] Explicitly delay wready_o assertions by a cycle
  hw/ip/prim/fpv/vip/prim_fifo_sync_assert_fpv.sv
Labels: Component:FPV, IP:prim

#24433 [prim,fpv] Fix delays in assertions of prim_fifo_async_sram_adapter
  hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv
Labels: Component:FPV, IP:prim

#24294 [pentest] Add RNG FI tests
  sw/device/tests/penetrationtests/firmware/BUILD
  sw/device/tests/penetrationtests/firmware/fi/BUILD
  sw/device/tests/penetrationtests/firmware/fi/rng_fi.c
  sw/device/tests/penetrationtests/firmware/fi/rng_fi.h
  sw/device/tests/penetrationtests/firmware/firmware.c
  sw/device/tests/penetrationtests/firmware/firmware_fi.c
  sw/device/tests/penetrationtests/json/BUILD
  sw/device/tests/penetrationtests/json/commands.h
  sw/device/tests/penetrationtests/json/rng_fi_commands.c
  sw/device/tests/penetrationtests/json/rng_fi_commands.h
Labels: Status:Ready to merge
