Repository lowRISC/opentitan, pull requests merged in 2024-10, with the labels that each got.

#24702 [tlul/rtl] Modify readback check error reporting logic
  hw/ip/tlul/rtl/tlul_sram_byte.sv
Labels: ECO

#24534 [rv_dm,dv] Improve modelling of system bringup in ndmreset sequence
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_ndmreset_req_vseq.sv
Labels: Component:DV, IP:rv_dm

#24549 [rv_dm,dv] Waive line coverage for DTM_ERR response from dm_top
  hw/ip/rv_dm/dv/cov/rv_dm_cov_excl.el
Labels: Component:DV, IP:rv_dm

#24568 [rv_dm,dv] Waive some impossible secded toggle coverage
  hw/ip/rv_dm/dv/cov/rv_dm_cov_excl.el
Labels: Component:DV, IP:rv_dm

#24533 [rv_dm,dv] Add a task that injects TL errors to the smoke sequence
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_smoke_vseq.sv
Labels: Component:DV, IP:rv_dm

#24700 [csr_utils_pkg,dv] Avoid bug on reset in csr_spinwait
  hw/dv/sv/csr_utils/csr_utils_pkg.sv
Labels: Component:DV, Type:Bug

#24563 [dv,vcs] Tidy up the comments where we disable coverage in a prim
  hw/dv/tools/vcs/cover.cfg
  hw/dv/tools/vcs/cover_reg_top.cfg
Labels: Component:DV

#22965 [prim] Remove prim_clock_gp_mux2
  SUMMARY.md
  hw/ip/prim/doc/prim_clock_gp_mux2.md
  hw/ip/prim/prim_clock_gp_mux2.core
  hw/ip/prim/rtl/prim_clock_gp_mux2.sv
Labels: Type:Cleanup, IP:prim

#24699 [sram_ctrl,dv] Add sec_cm_mem_readback test
  hw/dv/sv/mem_bkdr_scb/mem_bkdr_scb.sv
  hw/ip/sram_ctrl/data/sram_ctrl_sec_cm_testplan.hjson
  hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_base_vseq.sv
  hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_readback_err_vseq.sv
  hw/ip/sram_ctrl/dv/env/seq_lib/sram_ctrl_vseq_list.sv
  hw/ip/sram_ctrl/dv/env/sram_ctrl_env.core
  hw/ip/sram_ctrl/dv/env/sram_ctrl_env_cfg.sv
  hw/ip/sram_ctrl/dv/env/sram_ctrl_scoreboard.sv
  hw/ip/sram_ctrl/dv/sram_ctrl_base_sim_cfg.hjson
Labels: Component:DV, IP:sram_ctrl

#24724 [kmac/dv] Add sideload_invalid test.
  hw/ip/kmac/data/kmac_testplan.hjson
  hw/ip/kmac/dv/env/kmac_env.core
  hw/ip/kmac/dv/env/kmac_env_cfg.sv
  hw/ip/kmac/dv/env/kmac_scoreboard.sv
  hw/ip/kmac/dv/env/seq_lib/kmac_sideload_invalid_vseq.sv
  hw/ip/kmac/dv/env/seq_lib/kmac_vseq_list.sv
  hw/ip/kmac/dv/kmac_base_sim_cfg.hjson
  hw/ip/kmac/rtl/kmac_app.sv
  hw/ip/kmac/rtl/kmac_pkg.sv
Labels: Component:DV, IP:kmac

#24749 [topgen] Make toplevel SV and chiplevel templates top-sepcific
  hw/top_earlgrey/templates/chiplevel.sv.tpl
  hw/top_earlgrey/templates/toplevel.sv.tpl
  hw/top_englishbreakfast/templates/chiplevel.sv.tpl
  hw/top_englishbreakfast/templates/toplevel.sv.tpl
  util/topgen.py
Labels: Component:Tooling, Component:MultiTop

#24751 [hw,mbx,rtl] Gate TLUL error with valid signal
  hw/ip/mbx/rtl/mbx_sramrwarb.sv
Labels: Component:Darjeeling, IP:mailbox

#24763 [rv_dm,dv] Slightly broaden dependency in rv_dm_env.core
  hw/ip/rv_dm/dv/env/rv_dm_env.core
Labels: Component:DV, IP:rv_dm

#24770 [uart,doc] Redraw the block diagram
  hw/ip/uart/doc/block_diagram.svg
Labels: Component:Doc, IP:uart

#24794 [opentitanlib] Activate LED driver on HyperTeacup 1.5
  sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json
Labels: CherryPick:earlgrey_es_sival

#24569 [otbn,dv] Model a glitch on the STATUS register
  hw/ip/otbn/dv/otbnsim/sim/sim.py
Labels: Component:DV, IP:otbn

#24792 [sival,kmac] chip_sw_kmac_kmac_key_sideload
  hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
  sw/device/tests/BUILD
  sw/device/tests/kmac_kmac_key_sideload_test.c
Labels: CherryPick:earlgrey_1.0.0

#24753 [darjeeling] Add Darjeeling chip/toplevel SV template
  hw/top_darjeeling/templates/chiplevel.sv.tpl
  hw/top_darjeeling/templates/toplevel.sv.tpl
Labels: Component:MultiTop, Component:Darjeeling

#24859 [opentitantool] Support gpio analog-write via proxy
  sw/host/opentitanlib/src/proxy/handler.rs
  sw/host/opentitanlib/src/proxy/protocol.rs
  sw/host/opentitanlib/src/transport/proxy/gpio.rs
Labels: SW:opentitantool

#24912 [dv] Teach dv_base_reg to allow mubi regwen fields
  hw/dv/sv/dv_base_reg/dv_base_reg.sv
Labels: Component:DV

#24916 [hw,rstmgr,dv] Use Xcelium compatible syntax
  hw/ip_templates/rstmgr/dv/env/seq_lib/rstmgr_leaf_rst_shadow_attack_vseq.sv
  hw/ip_templates/rstmgr/dv/env/seq_lib/rstmgr_sec_cm_scan_intersig_mubi_vseq.sv
  hw/top_earlgrey/ip_autogen/rstmgr/dv/env/seq_lib/rstmgr_leaf_rst_shadow_attack_vseq.sv
  hw/top_earlgrey/ip_autogen/rstmgr/dv/env/seq_lib/rstmgr_sec_cm_scan_intersig_mubi_vseq.sv
Labels: Component:DV, IP:rstmgr

#24926 [tl_agent,dv] Disable covg_disable_cg for xcelium
  hw/dv/sv/tl_agent/dv/tb/tb.sv
  hw/dv/sv/tl_agent/dv/tl_agent_sim_cfg.hjson
Labels: Component:DV

#24928 [SPI,dv] Set strong drive strength and fast slew rate for SPI device
  sw/device/tests/BUILD
  sw/device/tests/spi_device_tpm_tx_rx_test.c
Labels: CherryPick:earlgrey_1.0.0
