Repository lowRISC/opentitan, pull requests merged in 2025-08, with the labels that each got.

#27569 [cryptolib,sw] Add instruction count checks to ECC functions
  sw/device/lib/crypto/impl/ecc/p256.c
  sw/device/lib/crypto/impl/ecc/p384.c
Labels: CherryPick:earlgrey_1.0.0

#27645 [ac_range_check,dv] Included logging support in testbench
  hw/ip_templates/ac_range_check/dv/ac_range_check_sim_cfg.hjson.tpl
  hw/ip_templates/ac_range_check/dv/env/ac_range_check_env.core.tpl
  hw/ip_templates/ac_range_check/dv/env/ac_range_check_env_cov.sv
  hw/ip_templates/ac_range_check/dv/env/ac_range_check_predictor.sv
  hw/ip_templates/ac_range_check/dv/env/ac_range_check_scoreboard.sv
  hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_base_vseq.sv
  hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_lock_range_vseq.sv
  hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_high_threshold_vseq.sv
  hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv
  hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_vseq_list.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/ac_range_check_sim_cfg.hjson
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env.core
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env_cov.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_predictor.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_scoreboard.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_base_vseq.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_lock_range_vseq.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_high_threshold_vseq.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_vseq_list.sv
Labels: Component:DV, IP:ac_range_check

#27592 [pentest] Return CryptoLib status code & bug fix
  sw/device/tests/penetrationtests/firmware/fi/cryptolib_fi_asym_impl.c
  sw/device/tests/penetrationtests/firmware/fi/cryptolib_fi_sym_impl.c
  sw/device/tests/penetrationtests/firmware/sca/cryptolib_sca_asym_impl.c
  sw/device/tests/penetrationtests/firmware/sca/cryptolib_sca_sym_impl.c
  sw/host/penetrationtests/testvectors/data/fi_asym_cryptolib.json
  sw/host/penetrationtests/testvectors/data/fi_sym_cryptolib.json
  sw/host/penetrationtests/testvectors/data/sca_asym_cryptolib.json
  sw/host/penetrationtests/testvectors/data/sca_sym_cryptolib.json
Labels: CherryPick:earlgrey_1.0.0

#27981 [util] fix bug in OTP image generation script
  util/design/gen-otp-img.py
Labels: CherryPick:master

#27998 [bazel,qemu] Stream QEMU stdout logs during test execution
  rules/scripts/qemu_pass.py
Labels: CherryPick:master
