Repository lowRISC/opentitan, pull requests merged in 2025-03, with the labels that each got.

#26483 [doc] Update SUMMARY for Darjeeling AC Range Check
  SUMMARY.md
Labels: Component:Doc, IP:ac_range_check

#26417 [ac_range_check,dv] Add alert registers to env_cfg
  hw/ip_templates/ac_range_check/dv/env/ac_range_check_env_cfg.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_env_cfg.sv
Labels: Component:DV, IP:ac_range_check

#26501 [top_darjeeling/dv] Remove non-existent `flash_ctrl` from config files
  hw/top_darjeeling/dv/top_darjeeling_sim_cfgs.hjson
  hw/top_darjeeling/lint/top_darjeeling_dv_lint_cfgs.hjson
Labels: Component:DV, Component:Darjeeling

#26438 [pentest] Read single int instead of array for num_enc
  sw/device/tests/penetrationtests/firmware/sca/BUILD
  sw/device/tests/penetrationtests/firmware/sca/aes_sca.c
  sw/device/tests/penetrationtests/firmware/sca/kmac_sca.c
  sw/device/tests/penetrationtests/firmware/sca/sha3_sca.c
  sw/device/tests/penetrationtests/json/aes_sca_commands.h
  sw/device/tests/penetrationtests/json/commands.h
Labels: CherryPick:earlgrey_1.0.0

#26517 [tl,dv] Fix infinite loop in tl_host_driver
  hw/dv/sv/tl_agent/tl_host_driver.sv
Labels: Component:DV

#26290 [sival/kmac] Add KMAC entropy stress test
  hw/top_earlgrey/data/ip/chip_kmac_testplan.hjson
  sw/device/tests/BUILD
  sw/device/tests/kmac_entropy_stress_test.c
Labels: CherryPick:master, CherryPick:earlgrey_1.0.0

#26514 [tlul,dv] Add do_compare function to tl_agent
  hw/dv/sv/tl_agent/tl_seq_item.sv
Labels: Component:DV, IP:tlul

#26442 Pattgen out of block scoreboard
  hw/ip/pattgen/dv/env/pattgen_scoreboard.sv
Labels: Component:DV, IP:pattgen

#25192 [prim,dv] Fix a failure mode for ASSERT_FPV_LINEAR_FSM
  hw/ip/prim/rtl/prim_assert.sv
Labels: Component:DV, IP:prim

#26500 [prim] Add mubix_logic_test_true_strict function
  hw/ip/prim/rtl/prim_mubi_pkg.sv
  util/design/data/prim_mubi_pkg.sv.tpl
Labels: IP:prim

#26590 [dv] Minor tidy-ups to dv_base_mem.sv
  hw/dv/sv/dv_base_reg/dv_base_mem.sv
Labels: Component:DV

#26601 [dv] Fix call to uvm_object_param_utils in tl_device_seq
  hw/dv/sv/tl_agent/seq_lib/tl_device_seq.sv
Labels: Component:DV, IP:tlul

#26587 [doc] Fix link to gpio.hjson in mdbook_dashboard.py
  util/mdbook_dashboard.py
Labels: Component:Doc

#26580 [pattgen,dv] Get rid of dead code in pattgen_base_vseq
  hw/ip/pattgen/dv/env/seq_lib/pattgen_base_vseq.sv
Labels: Component:DV, IP:pattgen

#26559 [rv_plic,rtl] Avoid an unnecessary ternary in a loop
  hw/ip_templates/rv_plic/rtl/rv_plic_gateway.sv.tpl
  hw/top_darjeeling/ip_autogen/rv_plic/rtl/rv_plic_gateway.sv
  hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_gateway.sv
  hw/top_englishbreakfast/ip_autogen/rv_plic/rtl/rv_plic_gateway.sv
Labels: Component:RTL, IP:rv_plic

#26599 [dv] Correctly use uvm_component_param_utils in key_sideload_agent
  hw/dv/sv/key_sideload_agent/key_sideload_agent.sv
  hw/dv/sv/key_sideload_agent/key_sideload_agent_cov.sv
  hw/dv/sv/key_sideload_agent/key_sideload_driver.sv
  hw/dv/sv/key_sideload_agent/key_sideload_monitor.sv
Labels: Component:DV, Type:Cleanup

#26631 [tlul,dv] Randomize instr_type to see EXECUTE type
  hw/dv/sv/cip_lib/seq_lib/cip_tl_host_single_seq.sv
Labels: Component:DV, IP:tlul

#26634 [dv_utils] Fix and improvements
  hw/dv/sv/dv_utils/dv_macros.svh
Labels: Component:DV

#26632 [tlul,dv] Add func to return intr_type bit pos
  hw/dv/sv/tl_agent/tl_agent_pkg.sv
Labels: Component:DV, IP:tlul

#26667 [tlul,dv] Fix seq calling cip_tl_host_single_seq
  hw/dv/sv/cip_lib/seq_lib/cip_base_vseq.sv
  hw/dv/sv/cip_lib/seq_lib/cip_tl_host_single_seq.sv
  hw/ip/rv_dm/dv/env/seq_lib/rv_dm_buffered_enable_vseq.sv
Labels: Component:DV, IP:tlul

#26612 [dv] Simplify DV_EOT_PRINT_TLM_FIFO_CONTENTS macro
  hw/dv/sv/dv_utils/dv_macros.svh
Labels: Component:DV, Type:Cleanup

#26676 [dvsim] Add -fs option for --fixed-seed
  util/dvsim/dvsim.py
Labels: Component:DV, Tool:dvsim

#26633 [ac_range_check,dv] Simplify compare_tl_a_chan task
  hw/ip_templates/ac_range_check/dv/env/ac_range_check_scoreboard.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/ac_range_check_scoreboard.sv
Labels: Component:DV, IP:ac_range_check

#26702 [racl_ctrl,rtl] Re-order racl_policy_t to match the register
  hw/top_darjeeling/rtl/autogen/top_racl_pkg.sv
  hw/top_earlgrey/rtl/autogen/top_racl_pkg.sv
  hw/top_englishbreakfast/rtl/autogen/top_racl_pkg.sv
  util/topgen/templates/top_racl_pkg.sv.tpl
Labels: Component:RTL, IP:racl_ctrl

#26591 [racl,doc] Import RACL RFC into documentation
  SUMMARY.md
  doc/contributing/hw/racl/README.md
  doc/contributing/hw/racl/connections.svg
  doc/contributing/hw/racl/implementation.svg
  doc/contributing/hw/racl/racl.svg
Labels: Component:Doc

#26687 [manuf] Align cert data before writing to flash info
  sw/device/silicon_creator/manuf/base/ft_personalize.c
Labels: CherryPick:earlgrey_1.0.0

#26715 [ipgen,doc] Add a missing back-tick in README.md
  util/ipgen/README.md
Labels: Component:Doc, Component:Tooling

#26738 [dv,rtl] Solve build warn from tlul_rsp_intg_gen
  hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv
Labels: Component:DV, Component:RTL, IP:tlul

#26731 [opentitanlib] Respect TPM burstCount
  sw/host/opentitanlib/src/tpm/driver.rs
Labels: SW:opentitantool

#26665 [ujson] Fix module identifier serialization
  sw/device/lib/base/status.c
  sw/device/lib/runtime/print.c
  sw/device/lib/runtime/print_unittest.cc
Labels: CherryPick:master

#26589 [ac_range_check/rtl] Fix permission checking and deny index
  hw/ip_templates/ac_range_check/rtl/ac_range_check.sv.tpl
  hw/top_darjeeling/ip_autogen/ac_range_check/rtl/ac_range_check.sv
Labels: Component:RTL, IP:ac_range_check

#26699 [ac_range_check,dv] Fix smoke to reveal RTL bug
  hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv
Labels: Component:DV, IP:ac_range_check

#26747 [epmp] Check the PMP address for NAPOT decode.
  sw/device/silicon_creator/lib/drivers/epmp.c
  sw/device/silicon_creator/lib/drivers/epmp.h
Labels: CherryPick:master

#26802 [ac_range_check,dv] Grant more transactions
  hw/ip_templates/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv
  hw/top_darjeeling/ip_autogen/ac_range_check/dv/env/seq_lib/ac_range_check_smoke_vseq.sv
Labels: Component:DV, IP:ac_range_check
